"""Pack generated skin poses into the game's aligned atlas format.

This only crops and packs authored art; it does not generate or recolor artwork.
Source sheets and their provenance are retained in art-source/complete-skins.
"""
from pathlib import Path
import json
from PIL import Image
import numpy as np
from scipy.ndimage import label

ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / 'art-source/complete-skins'
briefs = json.loads((SOURCE / 'manifest.json').read_text())
js = ['"use strict";', '// Generated by tools/art/complete_skins/build.py.']
assets = []
for b in briefs:
    key, sid = b['k'], b['set']
    im = Image.open(SOURCE / (key + '.png')).convert('RGBA')
    atlas = Image.new('RGBA', (576, 864))
    cells = [None]*54
    # Generated rows can drift vertically. Extract whole connected silhouettes,
    # rather than cutting at nominal grid boundaries (which can clip swords).
    for x in range(6):
        column = im.crop((round(x*im.width/6),0,round((x+1)*im.width/6),im.height))
        components, _ = label(np.array(column.getchannel('A')) >= 128)
        sizes = np.bincount(components.ravel()); sizes[0] = 0
        ids = sorted(range(1,len(sizes)),key=lambda j:sizes[j],reverse=True)[:9]
        if len(ids)!=9 or min(sizes[j] for j in ids)<2000:
            raise ValueError((key,x,'expected nine distinct authored silhouettes'))
        ids.sort(key=lambda j:np.where(components==j)[0].mean())
        for y, component in enumerate(ids):
            cell=column.copy()
            cell.putalpha(Image.fromarray(((components==component)*255).astype('uint8')))
            cells[y*6+x]=cell.crop(cell.getbbox())
    base_scale = 72 / cells[0].height
    for i, cell in enumerate(cells):
        scale = min(base_scale, 88/cell.width, 82/cell.height)
        cell = cell.resize((round(cell.width*scale), round(cell.height*scale)), Image.Resampling.NEAREST)
        atlas.alpha_composite(cell, ((i%6)*96+(96-cell.width)//2, (i//6)*96+90-cell.height))
    rel = f'assets/sprites/champions/{key}/skins/{sid}'
    out = ROOT / rel; out.mkdir(parents=True, exist_ok=True)
    atlas.save(out/'atlas.png'); atlas.crop((0,0,96,96)).save(out/'preview.png')
    meta = dict(w=96, h=96, cols=6, refH=72, anchor=90/96, fix={'left':'mirror'}, sets={})
    for direction, offset in [('down',0),('side',18),('up',36)]:
        for state, ids in dict(idle=[0,1],walk=[2,3,4,5],attack=[6,7,8],cast=[9,10,11],hit=[12],death=[13,14,15],ultimate=[16,17]).items():
            meta['sets'][state+'_'+direction] = [i+offset for i in ids]
    if key == 'iria': meta['sets']['walk_down'] = [2,~3,~4,5]
    if key == 'nigromante': meta['sets']['ult'] = [9,10,11,16,17]
    if key == 'libertador':
        meta['sets'].update(aim=[18,19],fire=[24,25,26],reload=[27,28,29],bayo_pre=[18,24],bayo_emb=[24,25,26],bayo_imp=[25,26],bayo_rem=[26,18],command=[27,28,29],cabral=[30,27,28],ult_cast=[34,35])
    pack = 'skin_'+sid
    js.append(f'champPackLoadAtlas({json.dumps(pack)},"{rel}/atlas.png",{json.dumps(meta)});')
    definition = dict(champ=key,name=b['name'].split(' — ')[-1],src=rel+'/preview.png',preview=rel+'/preview.png',packs={key:pack},preserveAuthoredArt=True)
    js.append(f'SET_SKINS[{json.dumps(sid)}]={json.dumps(definition,ensure_ascii=False)};')
    assets.extend([rel+'/atlas.png',rel+'/preview.png'])

# Mounted commander retains the specialized cavalry state machine.
im = Image.open(SOURCE/'libertador-horse.png').convert('RGBA')
horse = Image.new('RGBA',(1024,336))
scale = None
for i in range(18):
    x,y = i%8,i//8
    cell=im.crop((round(x*im.width/8),round(y*im.height/3),round((x+1)*im.width/8),round((y+1)*im.height/3)))
    cell.putalpha(cell.getchannel('A').point(lambda a:255 if a>=128 else 0))
    box=cell.getbbox()
    if not box: raise ValueError(('horse',i,'empty pose'))
    cell=cell.crop(box)
    if scale is None: scale=83/cell.height
    s=min(scale,120/cell.width,100/cell.height)
    cell=cell.resize((round(cell.width*s),round(cell.height*s)),Image.Resampling.NEAREST)
    horse.alpha_composite(cell,(x*128+(128-cell.width)//2,y*112+106-cell.height))
rel='assets/sprites/champions/libertador/skins/granadero/horse.png'
horse.save(ROOT/rel)
meta=dict(w=128,h=112,cols=8,refH=83,anchor=106/112,sets=dict(mount=[9,10,11,12],charge=[0,1,2,3,4],dismount=[5,6,7,8],m_idle=[13],m_atk=[14,15,16],m_run=[17,1,2]))
js.append(f'champPackLoadAtlas("skin_granadero_horse","{rel}",{json.dumps(meta)});')
js.append('SET_SKINS.granadero.packs.libertador_horse="skin_granadero_horse";')
assets.append(rel)
(ROOT/'js/assets/complete-set-skins-meta.js').write_text('\n'.join(js)+'\n')
(SOURCE/'assets.json').write_text(json.dumps(assets,indent=2)+'\n')
print(f'Packed {len(briefs)} skins, {len(briefs)*54} poses')
