"""Normalize approved generated sheets into aligned, binary-alpha game atlases."""
from pathlib import Path
from PIL import Image
import json,colorsys
import numpy as np
from scipy.ndimage import label
ROOT=Path(__file__).resolve().parents[3]
SETS=dict(brasa='ultimo_turno',eslabon='juramento_roto',morwen='vidrio_negro',farolero='lumbre_persistente',iria='hilo_umbral')
meta={'w':96,'h':96,'cols':6,'refH':72,'anchor':90/96,'fix':{'left':'mirror'},'sets':{}}
for d,off in [('down',0),('side',18),('up',36)]:
 for st,ids in dict(idle=[0,1],walk=[2,3,4,5],attack=[6,7,8],cast=[9,10,11],hit=[12],death=[13,14,15],ultimate=[16,17]).items():meta['sets'][st+'_'+d]=[i+off for i in ids]
js=['"use strict";','// Generated by tools/art/portadores/build.py; source poses retained in art-source.']
for k,s in SETS.items():
 im=Image.open(ROOT/'art-source/portadores'/f'{k}.png').convert('RGBA'); atlas=Image.new('RGBA',(576,864))
 im.putalpha(im.getchannel('A').point(lambda a:255 if a>=128 else 0))
 cuts={'brasa':[0,198,368,568,743,918,1105,1258,1403,1536],'eslabon':[0,181,333,509,666,819,991,1147,1303,1536],'morwen':[0,175,336,507,680,849,1021,1180,1342,1536],'farolero':[0,189,368,550,726,906,1086,1240,1398,1536],'iria':[0,184,353,518,696,867,1030,1193,1353,1536]}[k]
 ref=im.crop((0,0,round(im.width/6),cuts[1])).getbbox();baseScale=72/(ref[3]-ref[1])
 for i in range(54):
  x=i%6;y=i//6;cell=im.crop((round(x*im.width/6),cuts[y],round((x+1)*im.width/6),cuts[y+1]))
  mask=np.array(cell.getchannel('A'))>=128;components,n=label(mask);sizes=np.bincount(components.ravel());sizes[0]=0;keep=sizes>=max(12,sizes.max()*.04);keep[0]=False;cell.putalpha(Image.fromarray((keep[components]*255).astype('uint8')));box=cell.getbbox()
  if not box:raise ValueError((k,i,'empty'))
  cell=cell.crop(box);scale=min(baseScale,88/cell.width,82/cell.height);cell=cell.resize((round(cell.width*scale),round(cell.height*scale)),Image.Resampling.NEAREST)
  atlas.alpha_composite(cell,(x*96+(96-cell.width)//2,y*96+90-cell.height))
 out=ROOT/'assets/sprites/champions'/k;out.mkdir(parents=True,exist_ok=True);atlas.save(out/'atlas.png');atlas.crop((0,0,96,96)).save(out/'preview.png')
 skin=atlas.copy();pixels=skin.load()
 for y in range(skin.height):
  for x in range(skin.width):
   r,g,b,a=pixels[x,y]
   if a:
    h,sat,v=colorsys.rgb_to_hsv(r/255,g/255,b/255)
    # A restrained set palette; dark outlines and pale skin/highlights stay intact.
    if sat>.25 and .18<v<.88:
     r,g,b=colorsys.hsv_to_rgb((h+.10)%1,sat*.82,v);pixels[x,y]=(int(r*255),int(g*255),int(b*255),a)
 skin.save(out/'set.png');skin.crop((0,0,96,96)).save(out/'set-preview.png')
 js.append(f'champPackLoadAtlas({json.dumps(k)},"assets/sprites/champions/{k}/atlas.png",{json.dumps(meta)});')
 js.append(f'champPackCloneAtlas("skin_{s}",{json.dumps(k)},"assets/sprites/champions/{k}/set.png");')
 js.append(f'SET_SKINS["{s}"]={{champ:"{k}",name:"{s.replace("_"," ").title()}",src:"assets/sprites/champions/{k}/set-preview.png",preview:"assets/sprites/champions/{k}/set-preview.png",packs:{{{k}:"skin_{s}"}}}};')
(ROOT/'js/assets/portadores-meta.js').write_text('\n'.join(js)+'\n')
