"use strict";
/* Owner capability is always resolved by the server. This route grants no privileges. */
(function(){
 const options=document.getElementById('hub-options'); if(!options)return;
 const entry=node('button','Entrar como Game Master','btn'); entry.hidden=true;options.append(entry);
 let catalog={arenas:[],bosses:[],enemies:[]},serverCosmetics=[],root=null,content=null,notice=null,active='Resumen',generation=0,previousFocus=null,inertBefore=[];
 const tabs=['Resumen','Configuración','Eventos','Noticias y chat','Jugadores','Registro'];
 function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
 function say(text,error){if(notice){notice.textContent=text;notice.classList.toggle('gm-error',!!error);}}
 async function api(method,path,body){const r=await accountFetch(method,'/api/gm'+path,body);if(r.status<200||r.status>=300)throw Error(({CONFLICT:'El progreso o la configuración cambió. Volvé a cargar antes de guardar.',BAD_SCHEDULE:'Revisá las fechas: el fin debe ser posterior al inicio (máximo un año).',BAD_CONFIRMATION:'La confirmación no coincide o venció. Generá una nueva vista previa.',FORBIDDEN:'Esta acción requiere una cuenta OWNER.',NO_SAVE:'El jugador todavía no tiene progreso guardado.',BAD_CONFIG:'Usá multiplicadores entre 0,1 y 10.',UNSUPPORTED_EVENT_REWARD_BOSS:'Los jefes y recompensas de evento requieren una integración adicional.'})[r.j.error||r.j.code||r.j.msg]||r.j.msg||r.j.error||'No se pudo completar la operación.');return r.j;}
 function action(parent,label,fn,cls){const b=node('button',label,cls||'btn');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){say(e.message,true);}finally{b.disabled=false;}};parent.append(b);return b;}
 function field(parent,label,key,type,value){const box=node('label',undefined,'gm-field');box.append(node('span',label));const input=node(type==='textarea'?'textarea':'input');input.name=key;if(type!=='textarea')input.type=type||'text';if(value!==undefined)input.value=value;box.append(input);parent.append(box);return input;}
 function select(parent,label,key,items){const box=node('label',undefined,'gm-field');box.append(node('span',label));const input=node('select');input.name=key;for(const [value,text] of items){const opt=node('option',text);opt.value=value;input.append(opt);}box.append(input);parent.append(box);return input;}
 function panel(title,desc){if(!root)throw Error('Vista cerrada.');const s=node('section',undefined,'gm-card');s.append(node('h2',title));if(desc)s.append(node('p',desc));content.append(s);return s;}
 function form(parent,submit,handler){const f=node('form',undefined,'gm-form');parent.append(f);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{await handler(Object.fromEntries(new FormData(f)),f);}catch(err){say(err.message,true);}finally{b.disabled=false;}};const end=()=>{const b=node('button',submit,'btn');b.type='submit';f.append(b);};return {f,end};}
 function list(parent,rows,empty){if(!rows.length){parent.append(node('p',empty||'Todavía no hay registros.'));return;}const ul=node('ul',undefined,'gm-list');for(const row of rows)ul.append(node('li',row));parent.append(ul);}
 const numericLabels={xp:'Experiencia',gold:'Oro',drop:'Probabilidad de botín',enemyHp:'Vida de enemigos',enemyDamage:'Daño de enemigos',bossHp:'Vida de jefes',spawnRate:'Aparición de enemigos',difficulty:'Dificultad',eliteRate:'Élites'};
 function numbers(f,values){for(const [key,label] of Object.entries(numericLabels)){const i=field(f,label+' ×',key,'number',values[key]??1);i.min='.1';i.max='10';i.step='.1';}}
 const arenas=()=>catalog.arenas.map(id=>[id,typeof ARENA_MODS!=='undefined'?(ARENA_MODS[id]?.name||ARENA_MODS[id]?.label||id):id]);
 const cosmetics=()=>serverCosmetics.map(c=>[c.id,c.name+' · '+c.type]);
 async function summary(){const d=await api('GET','/dashboard');Object.assign(d,{onlineNow:d.online,activeMatches:d.activeMatchesEstimate,wins:d.victories,losses:d.defeats,averageDuration:Math.round((d.averageDurationMs||0)/1000),tutorialCompletion:d.tutorialCompleted,errors:d.metrics?.total?.error||0,champions:d.metrics?.dimensions?.champion,arenas:d.metrics?.dimensions?.arena,skins:d.metrics?.dimensions?.skin,sets:d.metrics?.dimensions?.set,funnel:d.metrics?.total});const s=panel('Alpha en vivo','Datos agregados de telemetría. La ausencia de registros no equivale a cero actividad.');const labels={onlineNow:'En línea ahora',usersToday:'Usuarios hoy',usersWeek:'Usuarios esta semana',usersMonth:'Usuarios este mes',accounts:'Cuentas',matches:'Partidas',activeMatches:'Partidas activas',averageDuration:'Duración media (s)',wins:'Victorias',losses:'Derrotas',abandons:'Abandonos',tutorialCompletion:'Tutoriales completados',errors:'Errores'};const grid=node('div',undefined,'gm-stats');for(const [k,label] of Object.entries(labels)){const card=node('div',undefined,'gm-stat');card.append(node('strong',d[k]??d.metrics?.[k]??'Sin datos'),node('span',label));grid.append(card);}s.append(grid);list(s,d.notes||[]);for(const [key,label] of [['champions','Campeones'],['arenas','Arenas'],['skins','Apariencias'],['sets','Sets'],['funnel','Recorrido de jugadores']]){const p=panel(label);const data=d[key]||{};list(p,Array.isArray(data)?data.map(r=>`${r.name||r.key||r.id}: ${r.count??r.value??0}`):Object.entries(data).map(([k,v])=>`${k}: ${typeof v==='number'?v:v.count??0}`));}}
 async function config(){const data=await api('GET','/config');const p=panel('Configuración normal','Valores permanentes. Los eventos aplican sus multiplicadores por separado y al terminar dejan de afectarlos.');const {f,end}=form(p,'Guardar configuración normal',async d=>{for(const k in d)d[k]=Number(d[k]);await api('PUT','/config',{version:data.version,config:d});await render('Configuración');say('Configuración normal guardada.');});numbers(f,data.config||data.normal||data);end();action(p,'Restaurar valores por defecto',async()=>{await api('POST','/config/defaults',{version:data.version});await render('Configuración');say('Valores normales restaurados.');});}
 async function events(){const data=await api('GET','/events');const p=panel('Crear evento','Un evento modifica temporalmente el mundo. Las fechas se muestran en la hora local del dispositivo.');const {f,end}=form(p,'Crear evento',async d=>{d.start=new Date(d.startsAt).getTime();d.end=new Date(d.endsAt).getTime();delete d.startsAt;delete d.endsAt;d.arenas=d.arena?[d.arena]:[];delete d.arena;d.wave=Number(d.wave);d.enemies=d.enemies?[d.enemies]:[];d.set=d.setId;d.cosmetic=d.cosmeticId;d.multipliers={};for(const key of ['xp','gold','drop']){d.multipliers[key]=Number(d[key]);delete d[key];}await api('POST','/events',d);await render('Eventos');say('Evento programado.');});for(const [label,key,type] of [['Nombre','name','text'],['Descripción','description','textarea'],['Banner (URL https)','banner','url'],['Inicio','startsAt','datetime-local'],['Fin','endsAt','datetime-local']]){const i=field(f,label,key,type);if(['name','startsAt','endsAt'].includes(key))i.required=true;}select(f,'Arena','arena',[['','Todas las arenas'],...arenas()]);for(const [label,key] of [['Oleada','wave']]){const i=field(f,label,key,'number',1);i.min=1;i.max=99;}
 field(f,'Jefe · integración pendiente','boss','text').disabled=true;select(f,'Enemigo especial','enemies',[['','Sin enemigo adicional'],...catalog.enemies.map(id=>[id,id])]);select(f,'Set · integración pendiente','setId',[['','Ninguno'],...(typeof SET_DB==='undefined'?[]:Object.entries(SET_DB).map(([id,s])=>[id,s.name||id]))]).disabled=true;select(f,'Cosmético de recompensa · integración pendiente','cosmeticId',[['','Ninguno'],...cosmetics()]).disabled=true;field(f,'Anuncio','announcement','textarea');for(const key of ['xp','gold','drop']){const i=field(f,numericLabels[key]+' ×',key,'number',1);i.min='.1';i.max='10';i.step='.1';}end();const q=panel('Eventos programados y activos');for(const e of data.events||[]){const card=node('article',undefined,'gm-record');card.append(node('h3',e.name),node('p',e.description||''),node('p',`${e.enabled===false?'FINALIZADO · ':e.start<=Date.now()&&e.end>Date.now()?'ACTIVO · ':'PROGRAMADO · '}${new Date(e.start).toLocaleString()} → ${new Date(e.end).toLocaleString()}`));if(e.enabled!==false)action(card,'Finalizar evento',async()=>{await api('POST','/events',{...e,enabled:false});await render('Eventos');say('Evento finalizado; configuración normal conservada.');});q.append(card);}if(!(data.events||[]).length)q.append(node('p','No hay eventos.'));}
 async function messages(){const scheduled=await api('GET','/messages');const p=panel('Noticias, banners y mensajes','Publicá anuncios con inicio y fin. El chat global conserva su propio historial.');const {f,end}=form(p,'Publicar anuncio',async d=>{d.start=d.startsAt?new Date(d.startsAt).getTime():Date.now();d.end=new Date(d.endsAt).getTime();d.text=(d.title?d.title+' — ':'')+d.text;delete d.startsAt;delete d.endsAt;delete d.title;await api('POST','/messages',d);say('Anuncio publicado.');});select(f,'Tipo','type',[['news','Noticia'],['banner','Banner'],['global','Mensaje destacado']]);field(f,'Título','title','text').required=true;field(f,'Texto','text','textarea').required=true;field(f,'Imagen (URL https)','image','url');field(f,'Inicio','startsAt','datetime-local');field(f,'Fin','endsAt','datetime-local').required=true;end();const scheduledPanel=panel('Anuncios programados');for(const m of scheduled.messages||[]){const row=node('article',undefined,'gm-record');row.append(node('p',m.text),node('p',new Date(m.start).toLocaleString()+' → '+new Date(m.end).toLocaleString()));if(m.enabled!==false)action(row,'Retirar anuncio',async()=>{await api('POST','/messages',{...m,enabled:false});await render('Noticias y chat');});scheduledPanel.append(row);}const q=panel('Chat global · Game Master');const chat=form(q,'Enviar como Game Master',async d=>{await accountFetch('POST','/api/chat',{text:d.text}).then(r=>{if(r.status!==200)throw Error(r.j.msg||'No se pudo enviar.');});say('Mensaje enviado.');chat.f.reset();});field(chat.f,'Mensaje','text','textarea').required=true;chat.end();const r=await accountFetch('GET','/api/chat');if(r.status!==200)throw Error(r.j.msg||'No se pudo leer el chat.');if(r.j.pinned){q.append(node('p','Fijado: '+r.j.pinned.text));action(q,'Desfijar mensaje',async()=>{await api('POST','/chat/pin',{id:null});await render('Noticias y chat');});}for(const m of r.j.messages||[]){const row=node('article',undefined,'gm-record');row.append(node('strong',(m.owner?'GAME MASTER · ':'')+m.name),node('p',m.text));action(row,'Fijar este mensaje',async()=>{await api('POST','/chat/pin',{id:m.id});say('Mensaje fijado.');});q.append(row);}}
 async function players(){const p=panel('Jugadores','Consultá un perfil antes de regalar o reiniciar progreso.');const detail=node('div');const search=form(p,'Buscar jugador',async d=>{const data=await api('GET','/players?q='+encodeURIComponent(d.user));detail.replaceChildren();for(const player of data.players||[])action(detail,player.name+' · '+player.user,async()=>{const r=await accountFetch('POST','/api/admin/profile',{user:player.user});if(r.status!==200)throw Error(r.j.msg||'No se pudo consultar el perfil.');detail.replaceChildren();drawProfile(r.j,detail);});if(!data.players?.length)detail.append(node('p','No se encontraron cuentas.'));});field(search.f,'Nombre de usuario','user','text').required=true;search.end();p.append(detail);const all=panel('Regalo para toda la Alpha','Entrega el cosmético a todas las cuentas existentes. No modifica estadísticas.');gift(all,'all');}
 function gift(parent,user){const {f,end}=form(parent,user==='all'?'Regalar a todos':'Regalar cosmético',async d=>{const r=await api('POST','/gift',{user,cosmetic:d.cosmeticId});say(`Regalos entregados: ${r.granted}. Conflictos: ${r.conflicts}. Cuentas sin progreso: ${r.missingSave}.`);});select(f,'Cosmético','cosmeticId',cosmetics()).required=true;end();}
 function drawProfile(p,parent){parent.append(node('h3',p.name||p.user),node('p','Versión del progreso: '+(p.version??'—')));list(parent,(p.champions||[]).filter(c=>c.unlocked).map(c=>`${c.key} · nivel ${c.level}`));gift(parent,p.user);const levels=node('section');levels.append(node('h3','Ajustar nivel de un campeón'),node('p','Al bajar el nivel se reinician sus talentos. Se conservan los objetos y el oro. El jugador debe sincronizar el progreso.'));parent.append(levels);const levelForm=form(levels,'Aplicar nivel',async d=>{const r=await accountFetch('POST','/api/admin/level',{user:p.user,champion:d.champion,level:Number(d.level),baseVersion:p.version});if(r.status!==200)throw Error(r.j.msg||'No se pudo actualizar el nivel.');parent.replaceChildren();drawProfile(r.j,parent);say('Nivel actualizado.');});select(levelForm.f,'Campeón','champion',(p.champions||[]).filter(c=>c.unlocked).map(c=>[c.key,c.key+' · '+c.level]));const levelInput=field(levelForm.f,'Nivel','level','number',1);levelInput.min=1;levelInput.max=99;levelInput.required=true;levelForm.end();const box=node('section',undefined,'gm-danger');box.append(node('h3','Reinicio granular'),node('p','Primero revisá qué datos se borrarán. El servidor crea un respaldo y preserva las métricas históricas.'));parent.append(box);const fields=[['championProgress','Progreso de campeones'],['arenas','Arenas desbloqueadas'],['gold','Oro'],['inventory','Inventario'],['cosmetics','Cosméticos'],['codex','Códice']];const preview=node('div');const {f,end}=form(box,'Previsualizar reinicio',async()=>{preview.replaceChildren();const selected=[...f.querySelectorAll('input:checked')].map(i=>i.name);if(!selected.length)throw Error('Seleccioná al menos un dato.');const r=await api('POST','/reset/preview',{user:p.user,fields:selected});preview.append(node('p','Cuentas afectadas: '+(r.accounts??1)),node('p','Se borrará: '+selected.map(k=>fields.find(x=>x[0]===k)[1]).join(', ')));for(const warning of r.warnings||[])preview.append(node('p',warning,'gm-error'));const phrase=r.confirmation||r.phrase||'REINICIAR';preview.append(node('p','Para confirmar, escribí exactamente: '+phrase));const confirm=form(preview,'Confirmar reinicio de los datos seleccionados',async d=>{if(d.confirmation!==phrase)throw Error('La frase no coincide.');await api('POST','/reset/confirm',{token:r.token,confirmation:d.confirmation});preview.replaceChildren(node('p','Reinicio completado y respaldado. El jugador debe sincronizar su perfil.'));say('Reinicio completado.');});field(confirm.f,'Frase de confirmación','confirmation','text').required=true;confirm.end();});for(const [key,label] of fields)field(f,label,key,'checkbox');end();box.append(preview);}
 async function audit(){const d=await api('GET','/dashboard');const p=panel('Registro administrativo','Acciones del owner, regalos y reinicios.');list(p,(d.actions||d.audit||[]).map(a=>`${new Date(a.at||a.createdAt).toLocaleString()} · ${a.action||a.type||''} · ${a.user||a.actor||a.owner||''} · ${a.target||''}`));}
 async function render(tab){if(!root)return;active=tab;const stamp=++generation;content.replaceChildren();say('Cargando…');root.querySelectorAll('[data-gm-tab]').forEach(b=>(b.disabled=true,b.setAttribute('aria-current',b.dataset.gmTab===tab?'page':'false')));try{await ({Resumen:summary,Configuración:config,Eventos:events,'Noticias y chat':messages,Jugadores:players,Registro:audit}[tab])();if(stamp===generation)say('');}catch(e){if(stamp===generation)say(e.message,true);}finally{if(root&&stamp===generation)root.querySelectorAll('[data-gm-tab]').forEach(b=>b.disabled=false);}}
 function close(){generation++;root?.remove();root=null;for(const [el,wasInert] of inertBefore)el.inert=wasInert;inertBefore=[];document.body.classList.remove('gm-open');previousFocus?.focus();}
 async function route(){if(location.hash!=='#game-master'){close();return;}try{const d=await api('GET','/status');if(!d.owner&&d.role!=='OWNER')throw Error('Esta ruta requiere una cuenta OWNER.');if(root)return;serverCosmetics=(await api('GET','/cosmetics')).cosmetics||[];catalog=await api('GET','/catalog');previousFocus=document.activeElement;root=node('main',undefined,'gm-shell');root.id='game-master';root.setAttribute('aria-label','Game Master');const header=node('header',undefined,'gm-header');header.append(node('h1','GAME MASTER'),node('span','ALPHA · OWNER','gm-badge'));action(header,'Entrar como jugador',()=>{location.hash='';});root.append(header);const nav=node('nav',undefined,'gm-nav');nav.setAttribute('aria-label','Secciones administrativas');for(const tab of tabs){const b=action(nav,tab,()=>render(tab));b.dataset.gmTab=tab;}root.append(nav);notice=node('p',undefined,'gm-notice');notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');root.append(notice);content=node('div',undefined,'gm-content');root.append(content);inertBefore=[...document.body.children].filter(el=>!['SCRIPT','STYLE','LINK'].includes(el.tagName)).map(el=>[el,el.inert]);for(const [el] of inertBefore)el.inert=true;document.body.append(root);document.body.classList.add('gm-open');root.querySelector('button').focus();await render(active);}catch(e){close();entry.hidden=true;const denied=node('section',undefined,'gm-denied');denied.setAttribute('role','alert');denied.append(node('p',e.message));action(denied,'Volver al juego',()=>{denied.remove();location.hash='';});document.body.append(denied);}}
 async function status(){entry.hidden=true;if(!acct.session){close();return;}try{const d=await api('GET','/status');entry.hidden=!(d.owner||d.role==='OWNER');}catch{}if(location.hash==='#game-master')await route();}
 entry.onclick=()=>{location.hash='game-master';};window.addEventListener('hashchange',route);window.addEventListener('account-change',status);status();
})();
