"use strict";
/* Owner capability is always resolved by the server. This route grants no privileges. */
(function(){
 const options=document.getElementById('hub-options'); if(!options)return;
 const entry=node('button','Entrar como Game Master','btn'); entry.hidden=true;options.append(entry);
 let catalog={arenas:[],bosses:[],enemies:[]},serverCosmetics=[],root=null,content=null,notice=null,active='Resumen',generation=0,previousFocus=null,inertBefore=[];
 const tabs=['Resumen','Configuración','Eventos','Noticias y chat','Jugadores','Reinicios','Registro'];
 function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
 function say(text,error){if(notice){notice.textContent=text;notice.classList.toggle('gm-error',!!error);}}
 async function api(method,path,body){const r=await accountFetch(method,'/api/gm'+path,body);if(r.status<200||r.status>=300)throw Error(({CONFLICT:'El progreso o la configuración cambió. Volvé a cargar antes de guardar.',BAD_SCHEDULE:'Revisá las fechas: el fin debe ser posterior al inicio (máximo un año).',BAD_CONFIRMATION:'La confirmación no coincide o venció. Generá una nueva vista previa.',FORBIDDEN:'Esta acción requiere una cuenta OWNER.',NO_SAVE:'El jugador todavía no tiene progreso guardado.',BAD_CONFIG:'Usá multiplicadores entre 0,1 y 10.',UNSUPPORTED_EVENT_REWARD_BOSS:'Los jefes y recompensas de evento requieren una integración adicional.'})[r.j.error||r.j.code||r.j.msg]||r.j.msg||r.j.error||'No se pudo completar la operación.');return r.j;}
 function action(parent,label,fn,cls){const b=node('button',label,cls||'btn');b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){say(e.message,true);}finally{b.disabled=false;}};parent.append(b);return b;}
 function field(parent,label,key,type,value){const box=node('label',undefined,'gm-field');box.append(node('span',label));const input=node(type==='textarea'?'textarea':'input');input.name=key;if(type!=='textarea')input.type=type||'text';if(value!==undefined)input.value=value;box.append(input);parent.append(box);return input;}
 function select(parent,label,key,items){const box=node('label',undefined,'gm-field');box.append(node('span',label));const input=node('select');input.name=key;for(const [value,text] of items){const opt=node('option',text);opt.value=value;input.append(opt);}box.append(input);parent.append(box);return input;}
 function panel(title,desc){if(!root)throw Error('Vista cerrada.');const s=node('section',undefined,'gm-card');s.append(node('h2',title));if(desc)s.append(node('p',desc));content.append(s);return s;}
 function form(parent,submit,handler){const f=node('form',undefined,'gm-form');parent.append(f);f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{await handler(Object.fromEntries(new FormData(f)),f);}catch(err){say(err.message,true);}finally{b.disabled=false;}};const end=()=>{const b=node('button',submit,'btn');b.type='submit';f.append(b);};return {f,end};}
 function list(parent,rows,empty){if(!rows.length){parent.append(node('p',empty||'Todavía no hay registros.'));return;}const ul=node('ul',undefined,'gm-list');for(const row of rows)ul.append(node('li',row));parent.append(ul);}
 const numericLabels={xp:'Experiencia',gold:'Oro',drop:'Probabilidad de botín',enemyHp:'Vida de enemigos',enemyDamage:'Daño de enemigos',bossHp:'Vida de jefes',spawnRate:'Aparición de enemigos',difficulty:'Dificultad',eliteRate:'Élites'};
 function numbers(f,values){for(const [key,label] of Object.entries(numericLabels)){const i=field(f,label+' ×',key,'number',values[key]??1);i.min='.1';i.max='10';i.step='.1';}}
 const arenas=()=>catalog.arenas.map(id=>[id,typeof ARENA_MODS!=='undefined'?(ARENA_MODS[id]?.name||ARENA_MODS[id]?.label||id):id]);
 const cosmetics=()=>serverCosmetics.map(c=>[c.id,c.name+' · '+c.type]);
 async function summary(){const d=await api('GET','/dashboard');Object.assign(d,{onlineNow:d.online,activeMatches:d.activeMatchesEstimate,wins:d.victories,losses:d.defeats,averageDuration:Math.round((d.averageDurationMs||0)/1000),tutorialCompletion:d.tutorialCompleted,errors:d.metrics?.total?.error||0,champions:d.metrics?.dimensions?.champion,arenas:d.metrics?.dimensions?.arena,skins:d.metrics?.dimensions?.skin,sets:d.metrics?.dimensions?.set,funnel:d.metrics?.total});const s=panel('Alpha en vivo','Datos agregados de telemetría. La ausencia de registros no equivale a cero actividad.');const labels={onlineNow:'En línea ahora',usersToday:'Usuarios hoy',usersWeek:'Usuarios esta semana',usersMonth:'Usuarios este mes',accounts:'Cuentas',matches:'Partidas',activeMatches:'Partidas activas',averageDuration:'Duración media (s)',wins:'Victorias',losses:'Derrotas',abandons:'Abandonos',tutorialCompletion:'Tutoriales completados',errors:'Errores'};const grid=node('div',undefined,'gm-stats');for(const [k,label] of Object.entries(labels)){const card=node('div',undefined,'gm-stat');card.append(node('strong',d[k]??d.metrics?.[k]??'Sin datos'),node('span',label));grid.append(card);}s.append(grid);list(s,d.notes||[]);for(const [key,label] of [['champions','Campeones'],['arenas','Arenas'],['skins','Apariencias'],['sets','Sets'],['funnel','Recorrido de jugadores']]){const p=panel(label);const data=d[key]||{};list(p,Array.isArray(data)?data.map(r=>`${r.name||r.key||r.id}: ${r.count??r.value??0}`):Object.entries(data).map(([k,v])=>`${k}: ${typeof v==='number'?v:v.count??0}`));}}
 async function config(){const data=await api('GET','/config');const p=panel('Configuración normal','Valores permanentes. Los eventos aplican sus multiplicadores por separado y al terminar dejan de afectarlos.');const {f,end}=form(p,'Guardar configuración normal',async d=>{for(const k in d)d[k]=Number(d[k]);await api('PUT','/config',{version:data.version,config:{...data.config,...d}});await render('Configuración');say('Configuración normal guardada.');});numbers(f,data.config||data.normal||data);end();action(p,'Restaurar valores por defecto',async()=>{await api('POST','/config/defaults',{version:data.version});await render('Configuración');say('Valores normales restaurados.');});
  const prices=panel('Precios en oro','Aplicá un precio especial por objeto, apariencia o campeón. Son valores de oro del juego; no hay pagos monetarios. Quitar un ajuste recupera el precio original.');
  const labels={itemPrices:'Objeto',cosmeticPrices:'Apariencia',championPrices:'Campeón'};
  const priceName=(kind,id)=>kind==='cosmeticPrices'?(serverCosmetics.find(c=>c.id===id)?.name||id):kind==='championPrices'&&typeof CLASSES!=='undefined'?(CLASSES[id]?.name||id):typeof ITEM_DB!=='undefined'?(ITEM_DB[id]?.name||id):id;
  const pf=form(prices,'Guardar precio en oro',async d=>{const value=Number(d.price);if(!d.id||!Number.isSafeInteger(value)||value<0||value>10000000)throw Error('Elegí contenido y un precio válido.');await api('PUT','/config',{version:data.version,config:{...data.config,[d.kind]:{...(data.config[d.kind]||{}),[d.id]:value}}});await render('Configuración');say('Precio en oro actualizado.');});
  const kind=select(pf.f,'Contenido','kind',Object.entries(labels));const item=select(pf.f,'Objeto, apariencia o campeón','id',[]);const price=field(pf.f,'Precio en oro','price','number',0);price.min=0;price.max=10000000;price.step=1;price.required=true;
  function priceOptions(){item.replaceChildren();for(const id of catalog.priceCatalog?.[kind.value]||[]){const o=node('option',priceName(kind.value,id));o.value=id;item.append(o);}price.value=data.config[kind.value]?.[item.value]??0;}
  kind.onchange=priceOptions;item.onchange=()=>{price.value=data.config[kind.value]?.[item.value]??0;};priceOptions();pf.end();
  for(const [key,label] of Object.entries(labels))for(const [id,value] of Object.entries(data.config[key]||{})){const row=node('article',undefined,'gm-record');row.append(node('p',label+' · '+priceName(key,id)+' · '+value+' oro'));action(row,'Restaurar precio de '+priceName(key,id),async()=>{const values={...data.config[key]};delete values[id];await api('PUT','/config',{version:data.version,config:{...data.config,[key]:values}});await render('Configuración');say('Precio original restaurado.');});prices.append(row);}
 }
 function localDate(ms){const d=new Date(ms);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
 const namedEnemy=id=>typeof ENEMY_BASE!=='undefined'?(ENEMY_BASE[id]?.name||id):id;
 async function events(){
  const data=await api('GET','/events');let editing=null;
  const p=panel('Crear o editar evento','Elegí contenido, condiciones y horario. El evento aplica sus ajustes temporalmente, sin modificar la configuración normal. Horas locales del dispositivo.');
  const {f,end}=form(p,'Guardar evento',async d=>{
   const payload={id:editing||undefined,name:d.name,description:d.description,banner:d.banner,start:new Date(d.startsAt).getTime(),end:new Date(d.endsAt).getTime(),enabled:true,
    arenas:[...arenaInput.selectedOptions].map(o=>o.value),enemies:[...enemyInput.selectedOptions].map(o=>o.value),wave:Number(d.wave),boss:d.boss,set:d.setId,cosmetic:d.cosmeticId,announcement:d.announcement,multipliers:{}};
   for(const key of Object.keys(numericLabels))payload.multipliers[key]=Number(d[key]);
   if(payload.end<=payload.start)throw Error('El fin debe ser posterior al inicio.');
   await api('POST','/events',payload);await render('Eventos');say(editing?'Evento actualizado.':'Evento programado.');
  });
  for(const [label,key,type,value] of [['Nombre','name','text',''],['Descripción','description','textarea',''],['Banner (URL https)','banner','url',''],['Inicio','startsAt','datetime-local',localDate(Date.now())],['Fin','endsAt','datetime-local',localDate(Date.now()+72*3600000)]]){const i=field(f,label,key,type,value);if(['name','startsAt','endsAt'].includes(key))i.required=true;}
  const arenaInput=select(f,'Arenas (sin selección: todas)','arenas',arenas());arenaInput.multiple=true;arenaInput.size=4;
  const enemyInput=select(f,'Enemigos especiales (opcional)','enemies',catalog.enemies.map(id=>[id,namedEnemy(id)]));enemyInput.multiple=true;enemyInput.size=4;
  const waveInput=field(f,'Desde la oleada','wave','number',1);waveInput.min=1;waveInput.max=10;waveInput.required=true;
  const bossInput=select(f,'Jefe de evento','boss',[['','Sin jefe adicional'],...Object.keys(catalog.bossArenaMap||{}).map(id=>[id,namedEnemy(id)])]);
  const bossHint=node('p','Los jefes conservan su arena y mecánicas originales. Seleccionar uno fija su arena y la oleada 10.','gm-field');f.append(bossHint);
  function bossScope(){const home=catalog.bossArenaMap?.[bossInput.value];arenaInput.disabled=!!home;waveInput.readOnly=!!home;if(home){for(const opt of arenaInput.options)opt.selected=opt.value===home;waveInput.value=10;}}
  bossInput.onchange=bossScope;
  select(f,'Set con botín destacado','setId',[['','Ninguno'],...(catalog.sets||[]).map(id=>[id,typeof SET_DB!=='undefined'?(SET_DB[id]?.name||id):id])]);
  select(f,'Cosmético por completar el evento','cosmeticId',[['','Ninguno'],...cosmetics()]);
  field(f,'Anuncio','announcement','textarea');numbers(f,{});end();
  const editingNotice=node('p','Nuevo evento');p.prepend(editingNotice);
  action(p,'Limpiar y crear otro',()=>{f.reset();bossScope();editing=null;editingNotice.textContent='Nuevo evento';f.elements.name.focus();});
  const q=panel('Eventos programados y activos');
  for(const e of data.events||[]){
   const card=node('article',undefined,'gm-record');const state=e.enabled===false?'FINALIZADO':e.end<=Date.now()?'TERMINADO':e.start<=Date.now()?'ACTIVO':'PROGRAMADO';
   card.append(node('h3',e.name),node('p',e.description||''),node('p',`${state} · ${new Date(e.start).toLocaleString()} → ${new Date(e.end).toLocaleString()}`),node('p','Arenas: '+(e.arenas?.join(', ')||'Todas')+' · Desde oleada '+e.wave),node('p','Jefe: '+(e.boss?namedEnemy(e.boss):'Ninguno')+' · Set: '+(e.set||'Ninguno')+' · Recompensa: '+(serverCosmetics.find(c=>c.id===e.cosmetic)?.name||'Ninguna')));
   action(card,'Editar evento',()=>{
    editing=e.id;editingNotice.textContent='Editando: '+e.name;
    for(const key of ['name','description','banner','announcement','boss'])f.elements[key].value=e[key]||'';
    f.elements.startsAt.value=localDate(e.start);f.elements.endsAt.value=localDate(e.end);f.elements.wave.value=e.wave;f.elements.setId.value=e.set||'';f.elements.cosmeticId.value=e.cosmetic||'';
    for(const key of Object.keys(numericLabels))f.elements[key].value=e.multipliers?.[key]??1;
    for(const opt of arenaInput.options)opt.selected=e.arenas?.includes(opt.value);for(const opt of enemyInput.options)opt.selected=e.enemies?.includes(opt.value);
    bossScope();p.scrollIntoView({block:'start'});f.elements.name.focus();
   });
   if(e.enabled!==false)action(card,'Finalizar evento',async()=>{await api('POST','/events',{...e,enabled:false});await render('Eventos');say('Evento finalizado; configuración normal conservada.');});q.append(card);
  }
  if(!(data.events||[]).length)q.append(node('p','No hay eventos.'));
 }

 async function messages(){const scheduled=await api('GET','/messages');const p=panel('Noticias, banners y mensajes','Publicá anuncios con inicio y fin. El chat global conserva su propio historial.');const {f,end}=form(p,'Publicar anuncio',async d=>{d.start=d.startsAt?new Date(d.startsAt).getTime():Date.now();d.end=new Date(d.endsAt).getTime();d.text=(d.title?d.title+' — ':'')+d.text;delete d.startsAt;delete d.endsAt;delete d.title;await api('POST','/messages',d);await render('Noticias y chat');say('Anuncio publicado.');});select(f,'Tipo','type',[['news','Noticia'],['banner','Banner'],['global','Mensaje destacado']]);field(f,'Título','title','text').required=true;field(f,'Texto','text','textarea').required=true;field(f,'Imagen (URL https)','image','url');field(f,'Inicio','startsAt','datetime-local');field(f,'Fin','endsAt','datetime-local').required=true;end();const scheduledPanel=panel('Anuncios programados');for(const m of scheduled.messages||[]){const row=node('article',undefined,'gm-record');row.append(node('p',m.text),node('p',new Date(m.start).toLocaleString()+' → '+new Date(m.end).toLocaleString()));if(m.enabled!==false)action(row,'Retirar anuncio',async()=>{await api('POST','/messages',{...m,enabled:false});await render('Noticias y chat');});scheduledPanel.append(row);}const q=panel('Chat global · Game Master');const chat=form(q,'Enviar como Game Master',async d=>{await accountFetch('POST','/api/chat',{text:d.text}).then(r=>{if(r.status!==200)throw Error(r.j.msg||'No se pudo enviar.');});await render('Noticias y chat');say('Mensaje enviado.');});field(chat.f,'Mensaje','text','textarea').required=true;chat.end();const r=await accountFetch('GET','/api/chat');if(r.status!==200)throw Error(r.j.msg||'No se pudo leer el chat.');if(r.j.pinned){q.append(node('p','Fijado: '+r.j.pinned.text));action(q,'Desfijar mensaje',async()=>{await api('POST','/chat/pin',{id:null});await render('Noticias y chat');});}for(const m of r.j.messages||[]){const row=node('article',undefined,'gm-record');row.append(node('strong',(m.owner?'GAME MASTER · ':'')+m.name),node('p',m.text));action(row,'Fijar este mensaje',async()=>{await api('POST','/chat/pin',{id:m.id});say('Mensaje fijado.');});q.append(row);}}
 async function players(){const p=panel('Jugadores','Consultá un perfil antes de regalar o reiniciar progreso.');const detail=node('div');const search=form(p,'Buscar jugador',async d=>{const data=await api('GET','/players?q='+encodeURIComponent(d.user));detail.replaceChildren();for(const player of data.players||[])action(detail,player.name+' · '+player.user,async()=>{const r=await accountFetch('POST','/api/admin/profile',{user:player.user});if(r.status!==200)throw Error(r.j.msg||'No se pudo consultar el perfil.');detail.replaceChildren();drawProfile(r.j,detail);});if(!data.players?.length)detail.append(node('p','No se encontraron cuentas.'));});field(search.f,'Nombre de usuario','user','text').required=true;search.end();p.append(detail);const all=panel('Regalo para toda la Alpha','Entrega el cosmético a todas las cuentas existentes. No modifica estadísticas.');gift(all,'all');await cohortGift();}
 async function cohortGift(){const events=await api('GET','/events');const p=panel('Regalos a participantes y cohorte Alpha','Entregá una apariencia a participantes autenticados de un evento o a cuentas creadas antes de una fecha.');const {f,end}=form(p,'Regalar a la cohorte',async d=>{const cohort=d.scope==='event'?{eventId:d.eventId}:{createdBefore:new Date(d.createdBefore).getTime()};if(d.scope==='event'&&!d.eventId)throw Error('Seleccioná un evento.');if(d.scope==='date'&&!Number.isFinite(cohort.createdBefore))throw Error('Indicá una fecha válida.');const r=await api('POST','/gift',{cohort,cosmetic:d.cosmeticId});say(`Regalos entregados: ${r.granted}. Conflictos: ${r.conflicts}. Cuentas sin progreso: ${r.missingSave}.`);});const scope=select(f,'Grupo','scope',[['event','Participantes de un evento'],['date','Cuentas Alpha creadas antes de una fecha']]);const event=select(f,'Evento','eventId',[['','Elegí un evento'],...(events.events||[]).map(e=>[e.id,e.name])]);const date=field(f,'Cuentas creadas antes de','createdBefore','datetime-local',localDate(Date.now()));select(f,'Cosmético','cosmeticId',cosmetics()).required=true;scope.onchange=()=>{event.closest('label').hidden=scope.value!=='event';date.closest('label').hidden=scope.value!=='date';};scope.onchange();end();}
 function gift(parent,user){const {f,end}=form(parent,user==='all'?'Regalar a todos':'Regalar cosmético',async d=>{const r=await api('POST','/gift',{user,cosmetic:d.cosmeticId});say(`Regalos entregados: ${r.granted}. Conflictos: ${r.conflicts}. Cuentas sin progreso: ${r.missingSave}.`);});select(f,'Cosmético','cosmeticId',cosmetics()).required=true;end();}
 function drawProfile(p,parent){parent.append(node('h3',p.name||p.user),node('p','Versión del progreso: '+(p.version??'—')));list(parent,(p.champions||[]).filter(c=>c.unlocked).map(c=>`${c.key} · nivel ${c.level}`));gift(parent,p.user);const levels=node('section');levels.append(node('h3','Ajustar nivel de un campeón'),node('p','Al bajar el nivel se reinician sus talentos. Se conservan los objetos y el oro. El jugador debe sincronizar el progreso.'));parent.append(levels);const levelForm=form(levels,'Aplicar nivel',async d=>{const r=await accountFetch('POST','/api/admin/level',{user:p.user,champion:d.champion,level:Number(d.level),baseVersion:p.version});if(r.status!==200)throw Error(r.j.msg||'No se pudo actualizar el nivel.');parent.replaceChildren();drawProfile(r.j,parent);say('Nivel actualizado.');});select(levelForm.f,'Campeón','champion',(p.champions||[]).filter(c=>c.unlocked).map(c=>[c.key,c.key+' · '+c.level]));const levelInput=field(levelForm.f,'Nivel','level','number',1);levelInput.min=1;levelInput.max=99;levelInput.required=true;levelForm.end();resetControls(parent,()=>({user:p.user}));}
 const resetStatus=s=>({completed:'Completado',conflict:'Conflicto: requiere nueva revisión',failed:'Falló: revisar antes de reintentar',prepared:'Respaldado; resultado aún no confirmado'})[s]||s;
 const resetFields=[['championProgress','Progreso de campeones'],['arenas','Arenas desbloqueadas'],['gold','Oro'],['inventory','Inventario'],['cosmetics','Cosméticos'],['codex','Códice']];
 function resetControls(parent,scope){
  const box=node('section',undefined,'gm-danger');box.append(node('h3','Reinicio granular'),node('p','Previsualizá los datos y cuentas afectados. Cada progreso se respalda antes de modificarlo; la telemetría histórica se conserva.'));parent.append(box);
  const preview=node('div');
  const {f,end}=form(box,'Previsualizar reinicio',async()=>{
   preview.replaceChildren();const selected=[...f.querySelectorAll('input:checked')].map(i=>i.name);if(!selected.length)throw Error('Seleccioná al menos un dato.');
   const r=await api('POST','/reset/preview',{...scope(),fields:selected});
   preview.append(node('p','Cuentas afectadas: '+r.accounts),node('p','Se borrará: '+selected.map(k=>resetFields.find(x=>x[0]===k)[1]).join(', ')));
   if(r.missingSave)preview.append(node('p','Cuentas sin progreso (no se modificarán): '+r.missingSave));
   if(r.players)list(preview,r.players.map(p=>p.user+' · versión '+p.version));
   for(const warning of r.warnings||[])preview.append(node('p',warning.replaceAll('CAS','control de versión').replaceAll('snapshot','respaldo'),'gm-error'));
   if(!r.token||!r.confirmation||!r.accounts)throw Error('No hay cuentas disponibles para reiniciar.');
   preview.append(node('p','Para confirmar, escribí exactamente: '+r.confirmation));
   const confirm=form(preview,'Confirmar reinicio de los datos seleccionados',async d=>{
    if(d.confirmation!==r.confirmation)throw Error('La frase no coincide.');
    let result;try{result=await api('POST','/reset/confirm',{token:r.token,confirmation:d.confirmation});}catch(error){preview.replaceChildren(node('p','La respuesta no confirmó el resultado. Revisá Reinicios → Historial de reinicios antes de volver a intentarlo.','gm-error'));throw error;}
    preview.replaceChildren(node('p','Cuentas reiniciadas y respaldadas: '+(result.completed??1)+'. Conflictos: '+(result.conflicts??0)+'.'));
    if(result.results)list(preview,result.results.map(row=>row.user+' · '+resetStatus(row.status)+(row.snapshot?' · respaldo '+row.snapshot:'')));
    preview.append(node('p','Los jugadores deben sincronizar el progreso. Los conflictos requieren una nueva previsualización.'));say('Reinicio procesado.');
   });field(confirm.f,'Frase de confirmación','confirmation','text').required=true;confirm.end();
  });
  for(const [key,label] of resetFields)field(f,label,key,'checkbox');end();box.append(preview);
  f.addEventListener('change',()=>preview.replaceChildren());
  return ()=>preview.replaceChildren();
 }
 async function resets(){
  const p=panel('Reinicios de progreso','Seleccioná cuentas concretas o toda la Alpha. Ningún dato cambia hasta revisar y confirmar la vista previa.');
  const mode=select(p,'Alcance','resetScope',[['selected','Cuentas seleccionadas'],['all','Todas las cuentas con progreso']]);
  const pick=node('div',undefined,'gm-player-picker');p.append(pick);const chosen=new Set();
  const search=form(pick,'Buscar cuentas',async d=>{const found=await api('GET','/players?q='+encodeURIComponent(d.query));results.replaceChildren();for(const user of found.players||[]){const input=field(results,user.name+' · '+user.user,user.user,'checkbox');input.checked=chosen.has(user.user);input.onchange=()=>{if(input.checked)chosen.add(user.user);else chosen.delete(user.user);count.textContent='Seleccionadas: '+chosen.size;invalidate();};}if(!found.players?.length)results.append(node('p','No se encontraron cuentas.'));});
  field(search.f,'Buscar por usuario (vacío muestra las primeras 100)','query','text');search.end();
  const count=node('p','Seleccionadas: 0');pick.append(count);const results=node('div',undefined,'gm-selection');pick.append(results);
  const invalidate=resetControls(p,()=>{if(mode.value==='all')return {user:'all'};if(!chosen.size)throw Error('Seleccioná al menos una cuenta.');return {users:[...chosen]};});
  mode.onchange=()=>{pick.hidden=mode.value==='all';invalidate();};
  const history=panel('Historial de reinicios','Si se interrumpe una operación, consultá aquí su resultado antes de volver a ejecutarla.');const reports=node('div');history.append(reports);async function refresh(){const data=await api('GET','/reset/batches');reports.replaceChildren();for(const batch of (data.batches||[]).slice().reverse()){const row=node('article',undefined,'gm-record');row.append(node('h3',new Date(batch.at).toLocaleString()),node('p','Lote: '+batch.id+' · '+(batch.finishedAt?'Procesado':'Resultado pendiente de confirmar')),node('p','Datos: '+(batch.fields||[]).map(k=>resetFields.find(f=>f[0]===k)?.[1]||k).join(', ')));list(row,(batch.results||[]).map(r=>r.user+' · '+resetStatus(r.status)+(r.snapshot?' · Respaldo: '+r.snapshot:'')));reports.append(row);}if(!data.batches?.length)reports.append(node('p','Todavía no hay reinicios.'));}action(history,'Actualizar historial',refresh);await refresh();
 }

 async function audit(){const d=await api('GET','/dashboard');const p=panel('Registro administrativo','Acciones del owner, regalos y reinicios.');list(p,(d.actions||d.audit||[]).map(a=>`${new Date(a.at||a.createdAt).toLocaleString()} · ${a.action||a.type||''} · ${a.user||a.actor||a.owner||''} · ${a.target||''}`));}
 async function render(tab){if(!root)return;active=tab;const stamp=++generation;content.replaceChildren();say('Cargando…');root.querySelectorAll('[data-gm-tab]').forEach(b=>(b.disabled=true,b.setAttribute('aria-current',b.dataset.gmTab===tab?'page':'false')));try{await ({Resumen:summary,Configuración:config,Eventos:events,'Noticias y chat':messages,Jugadores:players,Reinicios:resets,Registro:audit}[tab])();if(stamp===generation)say('');}catch(e){if(stamp===generation)say(e.message,true);}finally{if(root&&stamp===generation)root.querySelectorAll('[data-gm-tab]').forEach(b=>b.disabled=false);}}
 function close(){generation++;root?.remove();root=null;for(const [el,wasInert] of inertBefore)el.inert=wasInert;inertBefore=[];document.body.classList.remove('gm-open');previousFocus?.focus();}
 async function route(){document.querySelectorAll('.gm-denied').forEach(el=>el.remove());if(location.hash!=='#game-master'){close();return;}if(!acct.session && typeof accountOpen==='function'){accountOpen();return;}try{const d=typeof accountAdminAccess==='function'?await accountAdminAccess():await api('GET','/status');if(!d.owner&&d.role!=='OWNER')throw Error(d.message||'Esta ruta requiere una cuenta OWNER.');if(root)return;serverCosmetics=(await api('GET','/cosmetics')).cosmetics||[];catalog=await api('GET','/catalog');previousFocus=document.activeElement;root=node('main',undefined,'gm-shell');root.id='game-master';root.setAttribute('aria-label','Game Master');const header=node('header',undefined,'gm-header');header.append(node('h1','GAME MASTER'),node('span','ALPHA · OWNER','gm-badge'));action(header,'Entrar como jugador',()=>{location.hash='';});root.append(header);const nav=node('nav',undefined,'gm-nav');nav.setAttribute('aria-label','Secciones administrativas');for(const tab of tabs){const b=action(nav,tab,()=>render(tab));b.dataset.gmTab=tab;}root.append(nav);notice=node('p',undefined,'gm-notice');notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');root.append(notice);content=node('div',undefined,'gm-content');root.append(content);inertBefore=[...document.body.children].filter(el=>!['SCRIPT','STYLE','LINK'].includes(el.tagName)).map(el=>[el,el.inert]);for(const [el] of inertBefore)el.inert=true;document.body.append(root);document.body.classList.add('gm-open');root.querySelector('button').focus();await render(active);}catch(e){close();entry.hidden=!(typeof accountOwnerCandidate==='function'&&accountOwnerCandidate());const denied=node('section',undefined,'gm-denied');denied.setAttribute('role','alert');denied.append(node('p',e.message));action(denied,'Reintentar acceso al panel',()=>route());if(typeof accountOpen==='function')action(denied,'Entrar o cambiar de cuenta',()=>{denied.remove();location.hash='';accountOpen();});action(denied,'Volver al juego',()=>{denied.remove();location.hash='';});document.body.append(denied);}}
 let statusCheck=null;
 async function status(){
  const session=acct.session;
  if(!session){entry.hidden=true;close();return;}
  const candidate=typeof accountOwnerCandidate==='function'&&accountOwnerCandidate();
  if(candidate)entry.hidden=false;
  if(statusCheck)return;
  statusCheck=api('GET','/status');
  try{const d=await statusCheck;if(acct.session===session)entry.hidden=!(candidate||d.owner||d.role==='OWNER');}catch{if(acct.session===session)entry.hidden=!candidate;}
  finally{statusCheck=null;}
  if(acct.session!==session){status();return;}
  if(location.hash==='#game-master')await route();
 }
 window.gameMasterOpen=()=>{if(location.hash==='#game-master')route();else location.hash='game-master';};
 entry.onclick=window.gameMasterOpen;window.addEventListener('hashchange',route);window.addEventListener('account-change',status);status();
})();
