'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const {validate,scaffold,safeFile}=require('./contracts');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'horda-factory-'));
process.on('exit',()=>fs.rmSync(root,{recursive:true,force:true}));
const png=Buffer.alloc(24);Buffer.from([137,80,78,71,13,10,26,10]).copy(png);png.writeUInt32BE(128,16);png.writeUInt32BE(128,20);fs.writeFileSync(path.join(root,'atlas.png'),png);fs.writeFileSync(path.join(root,'evidence.txt'),'Fixture');
function valid(){const m=scaffold('fixture');for(const k of ['name','title','role','fantasy','lore','personality','silhouette'])m[k]='Fixture '+k;m.stats={hp:100,damage:10,speed:150};for(const a of [m.kit.basic,...m.kit.skills,m.kit.ultimate])for(const k of ['description','anticipation','execution','impact','feedback','vfx','sfx'])a[k]='description';m.kit.skills[0].maxTargets=5;m.kit.skills[0].hordeMechanism='chain';Object.keys(m.integration).forEach(k=>m.integration[k]='evidence.txt');Object.keys(m.evidence).forEach(k=>m.evidence[k]='evidence.txt');Object.assign(m.art,{atlas:'atlas.png',preview:'atlas.png',frameWidth:32,frameHeight:32,sha256:crypto.createHash('sha256').update(png).digest('hex'),review:{status:'PASS',reviewer:'fixture',evidence:'evidence.txt'}});Object.keys(m.art.animations).forEach(k=>m.art.animations[k]=1);m.cosmetics=['skin','croma','set'].map(type=>({id:type,name:type,type,champion:m.id,rarity:'common',tagline:'tagline',lore:'Alternative story',visualTheme:'forest',unlockSource:'alpha',collection:'alpha',vfxProfile:'default',visualChanges:[type==='croma'?'palette':'armor'],availability:'alpha-test',premiumPrice:null,preview:'atlas.png'}));m.set={sourceArena:'minas',pieces:['head','body'],rewardCosmetic:'set',rewardGrantsPower:false};return m;}
test('complete contract accepted structurally',()=>assert.deepEqual(validate(valid(),root),[]));
test('draft remains incomplete',()=>assert.ok(validate(scaffold('new'),root).length>25));
for(const [name,mutate,pattern] of [
 ['orphan',m=>m.cosmetics[0].champion='other',/champion mismatch/],['lore',m=>m.cosmetics[0].lore=m.lore,/lore must differ/],['recolor',m=>m.cosmetics[0].visualChanges=['palette','aura'],/palette\/aura/],['stats',m=>m.cosmetics[0].gameplayOverrides={hp:2},/modify gameplay/],['stat alias',m=>m.cosmetics[0].stats={hp:2},/modify gameplay/],['horde',m=>m.kit.skills[0].maxTargets=1,/multi-target/],['preview',m=>m.art.preview='missing.png',/preview must exist/],['set',m=>m.set.rewardCosmetic='missing',/set reward/],['hash',m=>m.art.sha256='bad',/hash must match/],['frames',m=>m.art.frameWidth=31,/align to frame/],['capacity',m=>m.art.animations.idle=999,/exceed atlas capacity/],['approval',m=>m.art.review.status='REDRAW',/visual review/],['evidence',m=>m.evidence.multiplayer='',/multiplayer evidence/],['budget',m=>m.budgets.particles=999,/particles/],['paywall',m=>m.cosmetics[0].premiumPrice=2,/monetary price/]])test(name,()=>{const m=valid();mutate(m);assert.ok(validate(m,root).some(e=>pattern.test(e)));});
test('path traversal and symlink rejected',()=>{assert.equal(safeFile('../outside',root),null);fs.symlinkSync('/etc/passwd',path.join(root,'escape'));assert.equal(safeFile('escape',root),null);});
