"""Normalize the commissioned 4x6 source sheet into the champion atlas."""
from pathlib import Path
from PIL import Image
import json

root = Path(__file__).resolve().parents[2]
source = Image.open(root / 'art-source/ynara/source.png').convert('RGBA')
alpha = source.getchannel('A').point(lambda x: 255 if x >= 128 else 0)
source.putalpha(alpha)
# Find the transparent gutter nearest each expected row boundary. This keeps
# detached halos while excluding neighboring rows, unlike bounding-box guesses.
cuts = [0]
for expected in [256, 512, 768, 1024, 1280]:
    blank = [y for y in range(expected-50, expected+51)
             if alpha.crop((0, y, source.width, y+1)).getbbox() is None]
    cuts.append(min(blank, key=lambda y: abs(y-expected)))
cuts.append(source.height)
atlas = Image.new('RGBA', (384, 576))
for row in range(6):
    for col in range(4):
        cell = source.crop((col*256, cuts[row], (col+1)*256, cuts[row+1]))
        box = cell.getbbox()
        if box is None:
            raise ValueError('Missing pose')
        cell = cell.crop(box)
        factor = min(76/cell.height, 84/cell.width)
        cell = cell.resize((round(cell.width*factor), round(cell.height*factor)), Image.Resampling.NEAREST)
        atlas.alpha_composite(cell, (col*96+(96-cell.width)//2, row*96+90-cell.height))
dest = root / 'assets/sprites/champions/ynara'
dest.mkdir(parents=True, exist_ok=True)
atlas.save(dest/'atlas.png', optimize=True)
atlas.crop((0, 0, 96, 96)).save(dest/'preview.png', optimize=True)
sets = {}
for direction, offset, cast in [('down',0,12),('side',4,16),('up',8,20)]:
    for state, frames in [('idle',[offset]), ('walk',list(range(offset,offset+4))),
                          ('attack',list(range(cast,cast+4))), ('cast',list(range(cast,cast+4))),
                          ('ultimate',list(range(cast,cast+4))), ('hit',[cast]), ('death',[cast])]:
        sets[state+'_'+direction] = frames
meta = dict(w=96,h=96,cols=4,refH=76,anchor=.9375,fix=dict(left='mirror'),sets=sets)
(root/'js/assets/ynara-meta.js').write_text('"use strict";\n// Generated by tools/art/build_ynara.py.\nchampPackLoadAtlas("ynara","assets/sprites/champions/ynara/atlas.png",'+json.dumps(meta)+');\nchampPackCloneAtlas("skin_santa_paciencia","ynara","assets/sprites/champions/ynara/atlas.png");\nSET_SKINS.santa_paciencia={champ:"ynara",name:"Santa Paciencia",src:"assets/sprites/champions/ynara/preview.png",preview:"assets/sprites/champions/ynara/preview.png",packs:{ynara:"skin_santa_paciencia"}};\n')
assert set(atlas.getchannel('A').get_flattened_data()) <= {0,255}
print('24 poses; 384x576; binary alpha; feet aligned at 90; PASS')
