const {chromium}=require('playwright'),{spawn}=require('child_process'),fs=require('fs');
const servers=[spawn('python3',['-m','http.server','8806'],{stdio:'ignore'}),spawn('node',['server/relay.js'],{env:{...process.env,PORT:'8818',DATABASE_URL:'',DATA_DIR:'/tmp/horda-duo-online'},stdio:'ignore'})];process.on('exit',()=>servers.forEach(s=>s.kill()));
(async()=>{await new Promise(r=>setTimeout(r,600));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const checks=[],errors=[],pages=[];const pairs=[['mago','eren'],['myla','iria'],['soporte','farolero'],['tanque','eslabon']];
for(const pair of pairs){const ctx=await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8806/?server=ws%3A%2F%2F127.0.0.1%3A8818');await p.waitForFunction(()=>typeof assetsAllReady==='function'&&assetsAllReady());await p.evaluate(([a,z])=>{save.starterChosen=true;for(const c of Object.values(save.champions)){c.unlocked=true;c.level=15;}selectedClass=a;save.duoReserve=z;currentArena='ciudad';setState('prep');renderPrepSummary();},pair);pages.push(p);}
const host=pages[0];await host.evaluate(()=>netCreateRoom(currentArena,selectedClass,15));const code=await host.evaluate(()=>net.code);for(const p of pages.slice(1))await p.evaluate(code=>netJoinRoom(code,selectedClass,15),code);await host.waitForFunction(()=>netHumanCount()===4);for(const p of pages.slice(1))await p.evaluate(()=>netSendLoadout(true));await host.waitForFunction(()=>[1,2,3].every(i=>netDuoLoadoutValid(i)));checks.push({name:'Four distinct full pairs',ok:await host.evaluate(()=>netDuplicateChamps().length===0)});
await host.evaluate(()=>netHostStartGame());for(const p of pages)await p.waitForFunction(()=>netMatch&&state==='playing');
await host.evaluate(()=>{setInterval(()=>{spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;enemies=[];},50);heroes[1].alive=false;});await pages[1].waitForFunction(()=>player.classKey==='iria'&&player.alive);checks.push({name:'Guest handoff replicated and controls refreshed',ok:await pages[1].evaluate(()=>selectedClass==='iria'&&player._duoUsed&&player.maxEnergy===CLASSES.iria.energyMax)});
const gx=await host.evaluate(()=>heroes[1].x);await pages[1].evaluate(()=>{joyVec={x:1,y:0};});await pages[1].waitForTimeout(700);await pages[1].evaluate(()=>{joyVec={x:0,y:0};});checks.push({name:'Guest can move after handoff',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)>5,gx)});
const deadx=await host.evaluate(()=>heroes[1].x);
await host.evaluate(()=>{heroes[1].alive=false;player.alive=false;});await host.waitForFunction(()=>player.classKey==='eren');await pages[1].waitForFunction(()=>!player.alive);await pages[2].waitForFunction(()=>heroes[0].classKey==='eren');checks.push({name:'Host card handoff reaches guests',ok:await pages[2].evaluate(()=>heroes[0]._duoUsed&&heroes[0].alive)});await pages[1].evaluate(()=>{joyVec={x:1,y:0};});await pages[1].waitForTimeout(400);checks.push({name:'Dead guest input cannot move authoritative hero',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)<1,deadx)});
checks.push({name:'Exhausted guest observes surviving team',ok:await pages[1].evaluate(()=>state==='playing'&&!player.alive)});
await host.evaluate(()=>{for(const h of heroes)h.alive=false;});await host.waitForTimeout(400);checks.push({name:'Pending reserves prevent early wipe',ok:await host.evaluate(()=>!runEnding&&heroes[2].classKey==='farolero'&&heroes[3].classKey==='eslabon')});await host.evaluate(()=>{for(const h of heroes)h.alive=false;});for(const p of pages)await p.waitForFunction(()=>state==='gameover');checks.push({name:'Eight deaths end all four clients',ok:true});
for(const p of pages)await p.evaluate(()=>{netFinishMatch();setState('prep');renderPrepSummary();});checks.push({name:'Returning to lobby restores original pairs',ok:(await Promise.all(pages.map((p,i)=>p.evaluate(pair=>selectedClass===pair[0]&&save.duoReserve===pair[1]&&duoValid(),pairs[i])))).every(Boolean)});
fs.writeFileSync('docs/ux/online-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));await b.close();servers.forEach(s=>s.kill());if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
})().catch(e=>{console.error(e);servers.forEach(s=>s.kill());process.exit(1)});
