'use strict';
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'horda-single-online-'));
const servers=[spawn('python3',['-m','http.server','8806'],{stdio:'ignore'}),spawn(process.execPath,['server/relay.js'],{env:{...process.env,PORT:'8818',DATABASE_URL:'',ACCOUNT_DATA_DIR:dir},stdio:'ignore'})];let browser;
(async()=>{await new Promise(r=>setTimeout(r,600));browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const checks=[],errors=[],pages=[],champs=['mago','myla','soporte','tanque'];
for(const champ of champs){const ctx=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8806/?server=ws%3A%2F%2F127.0.0.1%3A8818');await p.waitForFunction(()=>typeof assetsAllReady==='function'&&assetsAllReady());await p.evaluate(champ=>{save.starterChosen=true;save.tut={training:1};for(const c of Object.values(save.champions)){c.unlocked=true;c.level=15;}selectedClass=champ;save.duoReserve='eren';currentArena='ciudad';setState('prep');renderPrepSummary();},champ);pages.push(p);}
const host=pages[0];await host.evaluate(()=>netCreateRoom(currentArena,selectedClass,15));const code=await host.evaluate(()=>net.code);for(const p of pages.slice(1))await p.evaluate(code=>netJoinRoom(code,selectedClass,15),code);await host.waitForFunction(()=>netHumanCount()===4);for(const p of pages.slice(1))await p.evaluate(()=>netSendLoadout(true));await host.waitForFunction(()=>[1,2,3].every(i=>netDuoLoadoutValid(i)));
checks.push({name:'Four single-champion loadouts, no reserve',ok:await host.evaluate(()=>[1,2,3].every(i=>netLobby.loadouts[i].reserve==null)&&netDuplicateChamps().length===0)});
checks.push({name:'Host rejects duplicate main champion',ok:await host.evaluate(()=>{const old=net.room.slots[1].champ;net.room.slots[1].champ=net.room.slots[0].champ;const result=netDuplicateChamps().length>0&&netHostStartGame()===false&&!netMatch;net.room.slots[1].champ=old;return result;})});
await host.evaluate(()=>netHostStartGame());for(const p of pages)await p.waitForFunction(()=>netMatch&&state==='playing');
await host.evaluate(()=>{setInterval(()=>{spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;enemies=[];},50);heroes[1].alive=false;});await pages[1].waitForFunction(()=>!player.alive);
checks.push({name:'Downed guest retains champion, team continues',ok:await pages[1].evaluate(()=>player.classKey==='myla'&&state==='playing')});
const deadx=await host.evaluate(()=>heroes[1].x);await pages[1].evaluate(()=>{joyVec={x:1,y:0}});await pages[1].waitForTimeout(400);await pages[1].evaluate(()=>{joyVec={x:0,y:0}});checks.push({name:'Dead guest input cannot move authoritative hero',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)<1,deadx)});
// Five-second timing/damage cancellation is covered by test-single-champion-revive.
await host.evaluate(()=>reviveHero(heroes[1],player));await pages[1].waitForFunction(()=>player.alive);checks.push({name:'Host revival replicated without champion swap',ok:await pages[1].evaluate(()=>player.classKey==='myla')});
const gx=await host.evaluate(()=>heroes[1].x);await pages[1].evaluate(()=>{joyVec={x:1,y:0}});await pages[1].waitForTimeout(700);await pages[1].evaluate(()=>{joyVec={x:0,y:0}});checks.push({name:'Revived guest can move',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)>5,gx)});
await host.evaluate(()=>{player.alive=false;});await pages[2].waitForFunction(()=>!heroes[0].alive);checks.push({name:'Living guests prevent early defeat',ok:await host.evaluate(()=>!runEnding&&state==='playing')});
await host.evaluate(()=>{for(const h of heroes)h.alive=false});for(const p of pages)await p.waitForFunction(()=>state==='gameover');checks.push({name:'Team wipe ends all four clients',ok:true});
for(const p of pages)await p.evaluate(()=>{netFinishMatch();setState('prep');renderPrepSummary()});checks.push({name:'Lobby preserves original single champions',ok:(await Promise.all(pages.map((p,i)=>p.evaluate(champ=>selectedClass===champ&&duoValid(),champs[i])))).every(Boolean)});
fs.writeFileSync('docs/ux/online-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();servers.forEach(s=>s.kill());setTimeout(()=>fs.rmSync(dir,{recursive:true,force:true}),200)});
