const {chromium}=require('playwright'),{spawn}=require('child_process'),fs=require('fs');
const servers=[spawn('python3',['-m','http.server','8806'],{stdio:'ignore'}),spawn('node',['server/relay.js'],{env:{...process.env,PORT:'8818',DATABASE_URL:'',DATA_DIR:'/tmp/horda-duo-online'},stdio:'ignore'})];process.on('exit',()=>servers.forEach(s=>s.kill()));
(async()=>{await new Promise(r=>setTimeout(r,600));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const checks=[],errors=[],pages=[];const pairs=[['mago','eren'],['myla','iria'],['soporte','farolero'],['tanque','eslabon']];
for(const pair of pairs){const ctx=await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8806/?server=ws%3A%2F%2F127.0.0.1%3A8818');await p.waitForFunction(()=>typeof assetsAllReady==='function'&&assetsAllReady());await p.evaluate(([a,z])=>{save.starterChosen=true;for(const c of Object.values(save.champions)){c.unlocked=true;c.level=15;}selectedClass=a;save.duoReserve=z;currentArena='ciudad';setState('prep');renderPrepSummary();},pair);pages.push(p);}
const host=pages[0];await host.evaluate(()=>netCreateRoom(currentArena,selectedClass,15));const code=await host.evaluate(()=>net.code);for(const p of pages.slice(1))await p.evaluate(code=>netJoinRoom(code,selectedClass,15),code);await host.waitForFunction(()=>netHumanCount()===4);for(const p of pages.slice(1))await p.evaluate(()=>netSendLoadout(true));await host.waitForFunction(()=>[1,2,3].every(i=>netDuoLoadoutValid(i)));checks.push({name:'Four distinct champions',ok:await host.evaluate(()=>netDuplicateChamps().length===0)});
checks.push({name:'Host rejects duplicate champion',ok:await host.evaluate(()=>{const old=net.room.slots[1].champ;net.room.slots[1].champ='mago';const result=netDuplicateChamps().includes('mago')&&netHostStartGame()===false&&!netMatch;net.room.slots[1].champ=old;return result;})});
checks.push({name:'Host rejects missing player loadout',ok:await host.evaluate(()=>{const old=netLobby.loadouts[1];netLobby.loadouts[1]=null;const result=netHostStartGame()===false&&!netMatch;netLobby.loadouts[1]=old;return result;})});
await host.evaluate(()=>netHostStartGame());for(const p of pages)await p.waitForFunction(()=>netMatch&&state==='playing');
await host.evaluate(()=>{setInterval(()=>{spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;enemies=[];},50);heroes[1].alive=false;heroes[2].x=heroes[1].x+10;heroes[2].y=heroes[1].y;});
await pages[1].waitForFunction(()=>!player.alive);await pages[2].waitForFunction(()=>!heroes[1].alive);checks.push({name:'Death preserves original champion',ok:await pages[1].evaluate(()=>player.classKey==='myla'&&!player.alive)});
const deadx=await host.evaluate(()=>heroes[1].x);await pages[1].evaluate(()=>{joyVec={x:1,y:0};});await pages[1].waitForTimeout(400);await pages[1].evaluate(()=>{joyVec={x:0,y:0};});checks.push({name:'Dead guest input cannot move authoritative hero',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)<1,deadx)});
await pages[2].evaluate(()=>setReviveHold(heroes[1]));await host.waitForFunction(()=>heroes[1]._reviveT>0);await host.waitForTimeout(2200);await host.evaluate(()=>{const h=heroes[2];h.invulnTimer=0;damageHero(h,1,{x:h.x+20,y:h.y});h.stunTimer=1000;});await host.waitForTimeout(1500);checks.push({name:'Remote revive does not complete before five seconds',ok:await host.evaluate(()=>!heroes[1].alive&&heroes[1]._reviveT>3000&&heroes[1]._reviveT<5000)});
await pages[1].waitForFunction(()=>player.alive,{},{timeout:5000});checks.push({name:'Five-second revive survives hit and reaches guest',ok:await pages[1].evaluate(()=>player.classKey==='myla'&&player.hp>0)});
const gx=await host.evaluate(()=>heroes[1].x);await pages[1].evaluate(()=>{joyVec={x:1,y:0};});await pages[1].waitForTimeout(700);await pages[1].evaluate(()=>{joyVec={x:0,y:0};});checks.push({name:'Revived guest controls same hero',ok:await host.evaluate(x=>Math.abs(heroes[1].x-x)>5,gx)});
await host.evaluate(()=>{for(const h of heroes)h.alive=false;});for(const p of pages)await p.waitForFunction(()=>state==='gameover');checks.push({name:'Four deaths end four clients without reserves',ok:true});
for(const p of pages)await p.evaluate(()=>{netFinishMatch();setState('prep');renderPrepSummary();});checks.push({name:'Returning to lobby preserves one original champion',ok:(await Promise.all(pages.map((p,i)=>p.evaluate(pair=>selectedClass===pair[0]&&duoValid()&&duoKeys().length===1,pairs[i])))).every(Boolean)});
fs.writeFileSync('docs/ux/online-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors},null,2));await b.close();servers.forEach(s=>s.kill());if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
})().catch(e=>{console.error(e);servers.forEach(s=>s.kill());process.exit(1)});
