"""Import authored skin sheets. No drawing/recolor; preserve sources and stable save IDs."""
from pathlib import Path
import json
import numpy as np
from PIL import Image, ImageDraw
from scipy.ndimage import label, find_objects

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / 'art-source/unique-skins'
manifest = json.loads((SRC / 'manifest.json').read_text())
js = ['"use strict";', '// Generated by tools/art/unique_skins/build.py. Legacy IDs preserve ownership.',
      '// Independent authored designs use their own metadata, never cloned base frame indices.']
report = {}

def extract(entry):
    im = Image.open(SRC / entry['source']).convert('RGBA')
    mask, n = label(np.array(im.getchannel('A')) >= 160)
    sizes = np.bincount(mask.ravel()); sizes[0] = 0
    ids = [i for i in range(1, n+1) if sizes[i] > 600]
    expected = entry['cols'] * entry['rows']
    if len(ids) != expected:
        raise ValueError((entry['id'], 'separate silhouettes', len(ids), expected))
    boxes = find_objects(mask)
    # Group whole silhouettes into rows; grid lines may drift in generated source.
    ids.sort(key=lambda i: (boxes[i-1][0].start + boxes[i-1][0].stop)/2)
    ordered = []
    for r in range(entry['rows']):
        row = ids[r*entry['cols']:(r+1)*entry['cols']]
        ordered.extend(sorted(row, key=lambda i: (boxes[i-1][1].start+boxes[i-1][1].stop)/2))
    cells = []
    for index in entry['selected']:
        i = ordered[index]; sy, sx = boxes[i-1]
        cell = im.crop((sx.start, sy.start, sx.stop, sy.stop))
        cell.putalpha(Image.fromarray(((mask[sy,sx] == i)*255).astype('uint8')))
        cells.append(cell)
    return cells

def pack(entry, rel, horse=False):
    cells = extract(entry)
    w,h = (144,128) if horse else (112,112)
    foot = h-6; target = 86 if horse else 76
    scale = min(target/cells[0].height, (w-8)/max(c.width for c in cells), (h-12)/max(c.height for c in cells))
    cols = 4 if horse or len(cells)==12 else 8
    atlas = Image.new('RGBA',(w*cols,h*((len(cells)+cols-1)//cols)))
    bounds=[]
    for i,cell in enumerate(cells):
        cell=cell.resize((max(1,round(cell.width*scale)),max(1,round(cell.height*scale))),Image.Resampling.NEAREST)
        atlas.alpha_composite(cell,((i%cols)*w+(w-cell.width)//2,(i//cols)*h+foot-cell.height))
        bounds.append([cell.width,cell.height])
    out=ROOT/rel; out.parent.mkdir(parents=True,exist_ok=True);atlas.save(out)
    meta=dict(w=w,h=h,cols=cols,refH=bounds[0][1],anchor=foot/h,fix={'left':'mirror'},sets={})
    report[entry['id']]=dict(frames=len(cells),bounds=bounds,scale=scale,source=entry['source'],sourceSelection=entry['selected'])
    return meta,atlas

for e in manifest['skins']:
    sid,k=e['id'],e['champ'];rel=f'assets/sprites/champions/{k}/skins/{sid}'
    meta,atlas=pack(e,rel+'/atlas.png')
    for d,o in [('down',0),('side',8),('up',16)]:
        for st,indices in dict(idle=[0],walk=[1,0,2,0],run=[1,0,2,0],attack=[3,4,4],cast=[0,5,5],ultimate=[3,5,5],hit=[6],death=[6,7,7]).items():
            meta['sets'][st+'_'+d]=[o+i for i in indices]
    meta['sets']['run']=[9,8,10,8]
    if k=='cazadora': meta['sets']['aim']=[11]
    if k=='nigromante': meta['sets']['ult']=[3,5,5]
    if k=='libertador':
        meta['sets'].update(aim=[8],fire=[13],reload=[8,13,8],bayo_pre=[8,11],bayo_emb=[11,12],bayo_imp=[12],bayo_rem=[12,8],command=[13],cabral=[14,13],ult_cast=[11,13])
    atlas.crop((0,0,meta['w'],meta['h'])).save(ROOT/rel/'preview.png')
    packs={k:dict(src=rel+'/atlas.png',meta=meta)}
    if k=='libertador':
        ex=next(x for x in manifest['extra'] if x['id']=='horse_'+sid.split('_')[-1])
        m,_=pack(ex,rel+'/horse.png',True)
        m['sets']=dict(mount=[8,9,4],charge=[0,1,2,3],dismount=[10,11],m_idle=[4],m_atk=[5,6],m_run=[0,1,2,3])
        packs['libertador_horse']=dict(src=rel+'/horse.png',meta=m)
    if k=='myla':
        ex=next(x for x in manifest['extra'] if x['id']=='myla_berrinche_new')
        m,_=pack(ex,rel+'/berrinche.png')
        for d,o in [('down',0),('side',4),('up',8)]:
            for st in ['idle','walk','attack','cast','ultimate','hit']:
                m['sets'][st+'_'+d]=[o,o+1,o+2,o+3]
        packs['myla_berrinche']=dict(src=rel+'/berrinche.png',meta=m)
    data=dict(name=e['name'],lore=e['lore'],visualTheme=e['theme'],tagline=e['theme'],appearanceType='skin',rarity='Épica',preserveAuthoredArt=True,preview=rel+'/preview.png',files={},authoredPacks=packs)
    js.append(f'Object.assign(CROMA_SKINS[{json.dumps(sid)}],{json.dumps(data,ensure_ascii=False)});')
(ROOT/'js/assets/unique-skins-meta.js').write_text('\n'.join(js)+'\n')
(SRC/'frame-report.json').write_text(json.dumps(report,indent=2)+'\n')
print(f'Imported {len(manifest["skins"])} authored skins, {sum(r["frames"] for r in report.values())} frames')
