const {chromium}=require('playwright'),{spawn}=require('child_process'),fs=require('fs');
const servers=[spawn('python3',['-m','http.server','8795'],{stdio:'ignore'}),spawn('node',['server/relay.js'],{env:{...process.env,PORT:'8799'},stdio:'ignore'})];process.on('exit',()=>servers.forEach(s=>s.kill()));
(async()=>{await new Promise(r=>setTimeout(r,700));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),args:['--no-sandbox']});const checks=[],errors=[];
for(const [host,guest] of [['brasa','ynara'],['ynara','iria']]){
 const a=await (await b.newContext({viewport:{width:1000,height:560}})).newPage(),g=await (await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true})).newPage();for(const [p,c] of [[a,host],[g,guest]]){p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8795/?server=ws%3A%2F%2F127.0.0.1%3A8799');await p.waitForFunction(()=>typeof assetsAllReady==='function'&&assetsAllReady());await p.evaluate(c=>{save.starterChosen=true;for(const k in save.champions){save.champions[k].unlocked=true;save.champions[k].level=20;}selectedClass=c;currentArena='bosque';setState('prep');},c);}
 await a.evaluate(async()=>netCreateRoom(currentArena,selectedClass,20));const code=await a.evaluate(()=>net.code);await g.evaluate(async code=>netJoinRoom(code,selectedClass,20),code);await a.waitForFunction(()=>netHumanCount()===2);await g.evaluate(()=>{const s=PORTADORES[selectedClass].set;for(const slot in CHAMPION_SETS[s].pieces){const it=makeDesignedItem(s+'_'+slot);stashItems().push(it);save.champions[selectedClass].equipment[slot]=it.uid;}netSendLoadout(true);});await a.waitForTimeout(500);await a.evaluate(()=>netHostStartGame());await g.waitForFunction(()=>netMatch&&netMatch.role==='guest'&&state==='playing');
 await a.evaluate(()=>{spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;runLevel=ULT_MIN_ARENA_LEVEL;enemies=[];for(let j=0;j<5;j++){const e=spawnEnemy('esqueleto');Object.assign(e,{x:heroes[1].x+70+j*8,y:heroes[1].y,hp:1e6,maxHp:1e6,dmg:0,speed:0});}setInterval(()=>{spawnTimer=1e9;levelTimer=0;arenaHazardTimer=1e9;},100);});
 for(let i=0;i<3;i++){await g.evaluate(i=>{useSkill(i,{x:player.x+80,y:player.y,dx:1,dy:0});},i);await g.waitForTimeout(350);}await a.evaluate(()=>{for(let i=0;i<2;i++)useSkill(i,{x:player.x+50,y:player.y,dx:1,dy:0});});const active=await g.evaluate(()=>portadorObjects.map(o=>({kind:o.kind,owner:heroes.indexOf(o.owner)})));if(guest==='ynara')checks.push({name:'guest dish and curtain replicate',ok:active.some(o=>o.kind==='stroganoff'&&o.owner===1)&&active.some(o=>o.kind==='watercurtain'&&o.owner===1),active});await g.waitForTimeout(4500);
 await a.evaluate(()=>{heroes[1].ultCharge=heroes[1].ultMax;heroes[1].ultCd=0;});await g.waitForTimeout(250);await g.evaluate(()=>useUltimate());await g.waitForTimeout(500);if(host==='ynara'){await a.evaluate(()=>{player.ultCharge=player.ultMax;player.ultCd=0;useUltimate();});await g.waitForTimeout(400);const replicated=await g.evaluate(()=>portadorObjects.some(o=>o.kind==='patience'&&o.owner===heroes[0]));checks.push({name:'host Santa Paciencia replicates',ok:replicated});}
 const rh=await a.evaluate(()=>({classes:heroes.map(h=>h.classKey),casts:heroes[1].stats.skillCasts,objects:portadorObjects.map(o=>({kind:o.kind,owner:heroes.indexOf(o.owner)}))})),rg=await g.evaluate(()=>({k:player.classKey,casts:player.stats.skillCasts,objects:portadorObjects.map(o=>({kind:o.kind,owner:heroes.indexOf(o.owner)})),patience:portadorOwned(player,'patience').length,ready:CHAMP_PACK[player.classKey]?.ready,skin:setSkinPackKey(player,player.classKey)}));checks.push({host,guest,ok:rh.classes[1]===guest&&rg.k===guest&&rh.casts>=4&&(guest!=='ynara'||rg.patience===1)&&rg.ready&&rg.skin.startsWith('skin_')&&rg.objects.every(o=>o.owner>=0),rh,rg});console.log(JSON.stringify(checks[checks.length-1]));await g.screenshot({path:'docs/portadores/ynara-online-'+guest+'.png'});await a.context().close();await g.context().close();}
 fs.writeFileSync('docs/portadores/ynara-online-results.json',JSON.stringify({checks,errors},null,2));await b.close();servers.forEach(s=>s.kill());if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
})().catch(e=>{console.error(e);servers.forEach(s=>s.kill());process.exit(1)});
