const {chromium}=require('playwright'),fs=require('fs'),{spawn}=require('child_process');
const server=spawn('python3',['-m','http.server','8793'],{stdio:'ignore'});
(async()=>{let b;try{
 await new Promise(r=>setTimeout(r,400));b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8793');await p.waitForFunction(()=>CHAMP_PACK.ynara?.ready);
 const checks=await p.evaluate(()=>{
  const out=[],check=(name,ok)=>out.push({name,ok:!!ok});
  function start(arena='bosque'){netMatch=null;save.stash=[];for(const k in save.champions){Object.assign(save.champions[k],{unlocked:true,level:20,equipment:{},inventory:[],talents:{nodes:{},mastery:null,masteryNodes:{}}});}selectedClass='ynara';currentArena=arena;lobbyAllies=['tanque','soporte','mago'];startRun(3);enemies=[];spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;player.fx=1;player.fy=0;return player;}
  function enemy(dx=60,rank='normal'){const e=spawnEnemy('esqueleto');Object.assign(e,{x:player.x+dx,y:player.y,hp:1e7,maxHp:1e7,speed:0,dmg:0,rank});return e;}
  function cast(i,aim){player.aim=aim||{x:player.x+60,y:player.y};castAbility(player,i==='ult'?player.cls.ultimate:player.cls.skills[i],i==='ult',i==='ult'?undefined:i);}
  function tick(ms){for(let t=0;t<ms;t+=50){runElapsedMs+=50;for(const h of heroes)updatePortadorHero(h,50);updatePortadorObjects(50);}}
  start();const e=enemy(),boss=enemy(70,'jefe'),x=boss.x;cast(0);check('cone damages multiple targets',e.hp<1e7&&boss.hp<1e7);check('boss is not displaced',boss.x===x&&!(boss.knockTimer>0));check('boss slow capped',boss.slowAmt<=.12);
  start();const a=heroes[1];a.x=player.x;a.y=player.y;a.hp=a.maxHp*.5;player.hp=player.maxHp*.5;const target=enemy();cast(1,{x:player.x,y:player.y});cast(1,{x:player.x,y:player.y});check('one dish per owner',portadorOwned(player,'stroganoff').length===1);check('dish resistance',Math.abs(portadorTakenMult(player,null)-.92)<.001);const hp=player.hp,ah=a.hp;tick(650);check('dish heals self and ally',player.hp>hp&&a.hp>ah);check('dish steam damages',target.hp<1e7);check('healing capped at maximum',player.hp<=player.maxHp&&a.hp<=a.maxHp);tick(5000);check('dish expires',portadorOwned(player,'stroganoff').length===0);
  start();player.slowAmt=.4;player.slowTimer=1000;const old=player.x;cast(2);check('dash finite and bounded',player.x>old&&player.x-old<=180&&Number.isFinite(player.y));check('dash cleans slow',player.slowTimer===0);check('dash leaves curtain',portadorOwned(player,'watercurtain').length===1);tick(3000);check('curtain expires',portadorOwned(player,'watercurtain').length===0);
  start();tick(8000);check('passive shield capped',player.ynImmaculate&&player.shield<=player.maxHp*.08001);const pe=enemy(20);damageHero(player,player.maxHp,{type:'esqueleto'});check('shield break retaliation',!player.ynImmaculate&&pe.hp<1e7);check('no immediate shield rearm',(player.ynQuiet||0)<8000);
  start();const ue=enemy();cast('ult');const ult=portadorOwned(player,'patience')[0];for(let i=0;i<20;i++){runElapsedMs+=400;ynaraOnHit(heroes[1],1);heroes[1].x=player.x;heroes[1].y=player.y;}check('ultimate charge cap',ult.charges===8);player.x+=30;player.hp=player.maxHp*.5;tick(650);check('sanctuary follows owner',ult.x===player.x&&ult.y===player.y);check('sanctuary heals',player.hp>player.maxHp*.5);const eh=ue.hp;tick(6000);check('final wave and expiry',ue.hp<eh&&portadorOwned(player,'patience').length===0);
  start();const de=enemy();cast(1);cast('ult');player.alive=false;tick(50);check('death cancels all effects without explosion',portadorObjects.length===0&&de.hp===1e7);
  start();cast(1);cast('ult');_netHeroIdx=new Map(heroes.map((h,i)=>[h,i]));netMatch={snapN:0,last:{},lastG:{},lastH:[{},{},{},{}]};const snap=netBuildSnapshot(true,true);check('snapshot preserves owner slots',snap.c.portadorObjects.u.every(([id,o])=>o.owner.$h===0));netMatch=null;resetRunTransients();check('reset clears effects',portadorObjects.length===0);
  start();cast(1);const base=portadorOwned(player,'stroganoff')[0].heal;for(const slot in CHAMPION_SETS.santa_paciencia.pieces){const it=makeDesignedItem('santa_paciencia_'+slot);stashItems().push(it);save.champions.ynara.equipment[slot]=it.uid;}_passiveFrame++;check('four piece set and cosmetic',setN(player,'santa_paciencia')===4&&setSkinPackKey(player,'ynara')==='skin_santa_paciencia');cast(1);check('set healing bonus',portadorOwned(player,'stroganoff')[0].heal>base);const setHeal=portadorOwned(player,'stroganoff')[0].heal;save.champions.ynara.talents.nodes.ynara_t1a=3;cast(1);check('talent inactive before level 40',portadorOwned(player,'stroganoff')[0].heal===setHeal);save.champions.ynara.level=40;cast(1);check('talent increases dish healing from level 40',portadorOwned(player,'stroganoff')[0].heal>setHeal);
  for(const arena of ['bosque','hielo','laberinto','acuatica','fortaleza','micelial','ciudad','abismo','minas','infernal']){start(arena);enemy();for(let i=0;i<3;i++)cast(i);cast('ult');for(let i=0;i<30;i++)update(33);check('all casts in '+arena,Number.isFinite(player.hp)&&Number.isFinite(player.x)&&portadorObjects.length<=48);}
  check('atlas directions ready',CHAMP_PACK.ynara.ready&&CHAMP_PACK.ynara.sets.walk_up.length===4);
  start();cast(1,{x:player.x+60,y:player.y});cast('ult');return out;
 });await p.waitForTimeout(700);fs.mkdirSync('docs/ynara',{recursive:true});await p.screenshot({path:'docs/ynara/gameplay.png'});fs.writeFileSync('docs/ynara/functional-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,failed:checks.filter(c=>!c.ok),errors}));if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
 }finally{if(b)await b.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
