/* Real game regression and fixed-seed balance scenarios. Run from repository root. */
const {chromium}=require('playwright'),fs=require('fs'),{spawn}=require('child_process');
const server=spawn('python3',['-m','http.server','8792'],{stdio:'ignore'});process.on('exit',()=>server.kill());
(async()=>{await new Promise(r=>setTimeout(r,500));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1280,height:800}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8792');await p.waitForFunction(()=>typeof PORTADORES!=='undefined' && Object.keys(PORTADORES).every(k=>CHAMP_PACK[k].ready));await p.addScriptTag({path:'tools/balance/autopilot.js'});
const checks=await p.evaluate(()=>{
 const out=[],check=(name,ok,detail)=>out.push({name,ok:!!ok,detail});
 function start(k,arena='bosque'){netMatch=null;save.stash=[];for(const c in save.champions){save.champions[c].unlocked=true;save.champions[c].level=20;save.champions[c].equipment={};save.champions[c].inventory=[];save.champions[c].talents={nodes:{},mastery:null,masteryNodes:{}};}selectedClass=k;currentArena=arena;lobbyAllies=['tanque','soporte','mago'];startRun(3);enemies=[];spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;player.fx=1;player.fy=0;return player;}
 function enemy(dx=100,rank='normal'){const e=spawnEnemy('esqueleto');Object.assign(e,{x:player.x+dx,y:player.y,hp:1e7,maxHp:1e7,speed:0,baseSpeed:0,dmg:0,rank});return e;}
 function cast(i,aim){player.aim=aim||{x:player.x+100,y:player.y};castAbility(player,i==='ult'?player.cls.ultimate:player.cls.skills[i],i==='ult',i==='ult'?undefined:i);}
 function tick(ms){for(let t=0;t<ms;t+=50){runElapsedMs+=50;for(const h of heroes)updatePortadorHero(h,50);updatePortadorObjects(50);}}
 for(const k of ["myla"]){start(k);const e=enemy();for(let i=0;i<3;i++)cast(i);cast('ult');tick(3000);check(k+' all casts finite',Number.isFinite(player.hp)&&Number.isFinite(e.hp)&&portadorObjects.length<=48,{damage:1e7-e.hp});const ss=PORTADORES[k].set;for(const slot in CHAMPION_SETS[ss].pieces){const it=makeDesignedItem(ss+'_'+slot);stashItems().push(it);save.champions[k].equipment[slot]=it.uid;} _passiveFrame++;check(k+' set complete',setN(player,ss)===4 && setSkinPackKey(player,k)==='skin_'+ss,{count:setN(player,ss),pack:setSkinPackKey(player,k)});save.champions[k].talents.nodes[k+'_t0d']=5;check(k+' cooldown talent',Math.abs(talentSkillCdMult(k,0)-.85)<.001);}
 start('myla');const me=enemy(100);cast(0);cast(0);cast(0);check('Myla tower cap',portadorOwned(player,'turret').length===2);const mhp=me.hp;tick(2000);check('Myla towers damage and slow',me.hp<mhp&&me.slowTimer>0);cast(1);check('Myla yogurt puddle',portadorOwned(player,'yogurt').length===1);player.slowTimer=1000;cast(2);check('Myla protective bubble',player.shield>0&&player.slowTimer===0);cast('ult');check('Myla tantrum starts',portadorOwned(player,'tantrum').length===1);const thp=me.hp;player.x+=20;tick(1200);const tantrum=portadorOwned(player,'tantrum')[0];check('Myla crying follows and damages',tantrum.x===player.x&&me.hp<thp);tick(7000);check('Myla tantrum expires',portadorOwned(player,'tantrum').length===0);
 start('brasa');const e=enemy(140);cast(0);cast(0);cast(0);check('turret cap',portadorOwned(player,'turret').length===2);const before=e.hp;tick(1800);check('turret shoots',e.hp<before);cast('ult');tick(8100);check('overclock recovery',player.portCooldownTimer>0);tick(2200);check('recovery ends',player.portCooldownTimer===0);player.alive=false;tick(50);check('owner death removes constructs',portadorOwned(player,'turret').length===0);
 start('morwen');const m=enemy();cast(0);cast(1);check('reaction consumes both marks',m._portMarks[0].resin===0&&m._portMarks[0].salt===0&&player.portResidue===1);cast(2);check('distillation consumes residues',player.portResidue===0&&player.shield>0);for(let i=0;i<60;i++)portadorShield(player,.05,2000,player);check('shield capped',player.shield<=player.maxHp*.3+.001);
 for(const k of ['eslabon','brasa','farolero']){start(k);const e=enemy(100,'jefe'),x=e.x,y=e.y;cast(k==='eslabon'?0:1);check(k+' boss resists displacement',e.x===x&&e.y===y&&!(e.stunTimer>0)&&e.slowAmt<=.12);}
 start('farolero');const fe=enemy();cast(1);check('flash stuns common',fe.stunTimer===450);cast(0,{x:player.x,y:player.y});check('light remains local and weak',portadorLightAt(player.x,player.y)<=.24 && portadorLightAt(player.x+1000,player.y)===0);
 start('eslabon');const a=heroes[1];a.x=player.x+30;a.y=player.y;cast(2,{x:a.x,y:a.y});const hp=a.hp,guardHp=player.hp;damageHero(a,40,{type:'esqueleto'});check('custody transfers bounded damage',a.hp<hp&&player.hp<guardHp&&player.portGuardBudget>=0);player.invulnTimer=1000;const budget=player.portGuardBudget;damageHero(a,40,{type:'esqueleto'});check('immune custodian cannot absorb for free',budget===player.portGuardBudget);
 start('iria');for(const [x,y] of [[0,-60],[-60,50],[60,50],[0,-60]])cast(0,{x:player.x+x,y:player.y+y});check('anchor cap',portadorOwned(player,'anchor').length===3);cast('ult');check('triangle has finite geometry',portadorOwned(player,'triangle').every(o=>['ax','ay','bx','by','cx','cy'].every(k=>Number.isFinite(o[k]))));
 start('eslabon');const ally=heroes[1];ally.x=player.x+20;ally.y=player.y;cast(2,{x:ally.x,y:ally.y});const baseBudget=player.portGuardBudget;save.champions.eslabon.talents.nodes.eslabon_t2a=3;cast(2,{x:ally.x,y:ally.y});check('Custody power talent increases protection budget',player.portGuardBudget>baseBudget);
 start('brasa');cast(2);const baseSpeed=portadorSpeedMult(player);save.champions.brasa.talents.nodes.brasa_t2a=3;cast(2);check('Dismantle power talent increases speed',portadorSpeedMult(player)>baseSpeed);
 start('farolero');cast(2,{x:player.x+100,y:player.y});const baseReduction=portadorTakenMult(player,null);save.champions.farolero.talents.nodes.farolero_t2a=3;cast(2,{x:player.x+100,y:player.y});check('Safe Path power talent improves environment protection',portadorTakenMult(player,null)<baseReduction);
 start('iria');save.champions.iria.talents.nodes.iria_t0a=3;check('Anchor talent explicitly improves duration',talentSkillMods('iria',0).durationMult>0 && talentSkillMods('iria',0).powerMult===0);
 const irSet=PORTADORES.iria.set;for(const slot in CHAMPION_SETS[irSet].pieces){const item=makeDesignedItem(irSet+'_'+slot);stashItems().push(item);save.champions.iria.equipment[slot]=item.uid;}_passiveFrame++;
 cast('ult');cast(0,{x:player.x+200,y:player.y});cast(2,{x:player.x+200,y:player.y});check('Fallback triangle rejects unrelated anchor set proc',!player.portTriangleCut);
 portadorReset();for(const [x,y] of [[0,-60],[-60,50],[60,50]])cast(0,{x:player.x+x,y:player.y+y});cast('ult');const triangle=portadorOwned(player,'triangle')[0];check('Triangle records actual anchor identities',triangle.anchorIds.length===3);cast(2,{x:player.x,y:player.y-60});check('Actual triangle anchor triggers set proc once',player.portTriangleCut);player.portTriangleCut=false;const extra=portadorAdd(player,'anchor',{x:player.x+200,y:player.y},16000,{r:30});cast(2,{x:extra.x,y:extra.y});check('Unrelated later anchor rejects triangle set proc',!player.portTriangleCut);
 _netHeroIdx=new Map(heroes.map((h,i)=>[h,i]));netMatch={snapN:0,last:{},lastG:{},lastH:[{},{},{},{}]};const snap=netBuildSnapshot(true,true),serialized=JSON.stringify(snap);check('construct snapshots include owner slot',serialized.includes('"portadorObjects"')&&snap.c.portadorObjects.u.every(([id,o])=>o.owner&&o.owner.$h===0));check('snapshots remain bounded',serialized.length<300000,{bytes:serialized.length});netMatch=null;resetRunTransients();check('reset clears constructs',portadorObjects.length===0);
 for(const k in PORTADORES)for(const arena of ['bosque','hielo','laberinto','acuatica','fortaleza','micelial','ciudad','abismo','minas','infernal']){start(k,arena);enemy();for(let i=0;i<3;i++)cast(i);cast('ult');for(let i=0;i<30;i++)update(33);check(k+' arena '+arena,Number.isFinite(player.hp)&&portadorObjects.length<=48);}
 return out;
});console.log(JSON.stringify({checks:checks.length,failed:checks.filter(x=>!x.ok),errors}));
const runs=[];for(const k of ['myla'])for(const seed of [117,431,991]){
 const r=await p.evaluate(([k,seed])=>{let n=seed;Math.random=()=>{n=(1664525*n+1013904223)>>>0;return n/4294967296;};netMatch=null;save.stash=[];save.relics={hp:0,dmg:0,def:0,vel:0};for(const c in save.champions){save.champions[c].skillMastery=[0,1,2].map(()=>({...mkMastery(),alloc:4}));save.champions[c].ultMastery={...mkMastery(),alloc:4};save.champions[c].xp=0;save.champions[c].level=20;save.champions[c].unlocked=true;save.champions[c].equipment={};save.champions[c].inventory=[];save.champions[c].talents={nodes:{},mastery:null,masteryNodes:{}};}lobbyAllies=['tanque','soporte','mago'].map(c=>c===k?'guerrero':c);__AP.start(k,'bosque',1);for(let i=0;i<30;i++){const s=__AP.sim(5000,33.333);if(!['playing','buff'].includes(s.state))break;}const result={k,seed,state,level:runLevel,kills,hp:player.hp,maxHp:player.maxHp,damage:player.stats.dmgDealt,casts:player.stats.skillCasts,shieldAbsorbed:player.stats.shieldAbsorbed,error:__AP.err||null,objects:portadorObjects.length};__AP.on=false;setState('paused');return result;},[k,seed]);runs.push(r);console.log(JSON.stringify(r));}
fs.mkdirSync('docs/portadores',{recursive:true});fs.writeFileSync('docs/portadores/myla-simulation-results.json',JSON.stringify({checks,runs,errors},null,2));await p.screenshot({path:'docs/portadores/myla-gameplay.png'});await b.close();server.kill();if(errors.length||checks.some(c=>!c.ok)||runs.some(r=>r.error))process.exitCode=1;
})().catch(e=>{console.error(e);server.kill();process.exit(1)});
