'use strict';
const {chromium}=require('playwright'),fs=require('node:fs');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),args:['--no-sandbox']});try{const p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.ENTRY_BASE_URL||'http://127.0.0.1:8806');await p.waitForFunction(()=>typeof EXPEDITION!=='undefined'&&typeof CHAMPION_ENTRY_BALANCE!=='undefined');const checks=await p.evaluate(()=>{
 const out=[],check=(name,ok,details)=>out.push({name,ok:!!ok,...(details?{details}:{})});
 function start(k,arena='bosque',level=1){netMatch=null;save.stash=[];save.relics={hp:0,dmg:0,def:0,vel:0};for(const c in save.champions){Object.assign(save.champions[c],{unlocked:true,level,equipment:{},inventory:[],talents:{nodes:{},mastery:null,masteryNodes:{}}});save.champions[c].skillMastery=[0,1,2].map(()=>mkMastery());save.champions[c].ultMastery=mkMastery();}selectedClass=k;currentArena=arena;lobbyAllies=['tanque','soporte','mago'];startRun(3);enemies=[];spawnTimer=1e9;arenaHazardTimer=1e9;levelTimer=0;player.fx=1;player.fy=0;player.aim={x:player.x+60,y:player.y};runStats.critChance=0;return player;}
 function enemy(dx=40,rank='normal'){const e=spawnEnemy('esqueleto');Object.assign(e,{x:player.x+dx,y:player.y,hp:1e7,maxHp:1e7,dmg:0,speed:0,rank});return e;}
 function cast(i){castAbility(player,i==='ult'?player.cls.ultimate:player.cls.skills[i],i==='ult',i==='ult'?undefined:i);}
 function tick(ms){for(let t=0;t<ms;t+=50){runElapsedMs+=50;for(const h of heroes)updatePortadorHero(h,50);updatePortadorObjects(50);}}
 for(const k of Object.keys(EXPEDITION)){
  start(k);const es=[enemy(25),enemy(30),enemy(45)];for(let i=0;i<3;i++)cast(i);cast('ult');tick(2600);check(k+' level 1 horde damage',es.filter(e=>e.hp<1e7).length>=2);
  for(let n=0;n<15;n++){for(let i=0;i<3;i++)cast(i);cast('ult');}check(k+' bounded entities',portadorObjects.filter(o=>o.owner===player&&o.life>0).length<=8);check(k+' finite resources',Number.isFinite(player.hp)&&Number.isFinite(player.x)&&Number.isFinite(exState(player).heat));player.alive=false;tick(50);check(k+' death cleanup',!portadorObjects.some(o=>o.owner===player&&o.life>0)&&player.exState===null);
  start(k);const boss=enemy(30,'jefe'),pos={x:boss.x,y:boss.y};for(let i=0;i<3;i++)cast(i);cast('ult');tick(4000);check(k+' boss resists displacement/control',boss.x===pos.x&&boss.y===pos.y&&!(boss.knockTimer>0)&&!(boss.stunTimer>0)&&!(boss.slowAmt>.120001));
  start(k);cast('ult');tick(10000);check(k+' timed objects expire',!portadorObjects.some(o=>o.owner===player&&o.life>0));
  start(k);const id='exp_'+k;for(const slot in CHAMPION_SETS[id].pieces){const it=makeDesignedItem(id+'_'+slot);stashItems().push(it);save.champions[k].equipment[slot]=it.uid;}_passiveFrame++;check(k+' real set bonuses',setN(player,id)===4&&passiveSum(k,'hp_mult')>=.05&&passiveSum(k,'skilldmg_mult')>=.04);const old=talentSkillCdMult(k,0);save.champions[k].talents.nodes[k+'_t0c']=3;check(k+' cooldown talent',talentSkillCdMult(k,0)<old);
  // Maximum allowed talent ranks plus mastery: stability/limits, not balance certification.
  const tree=TALENT_TREES[k];for(const n of tree.nodes)save.champions[k].talents.nodes[n.id]=n.maxRank;save.champions[k].talents.mastery=k+'_0';for(const n of tree.masteries[k+'_0'].miniTree)save.champions[k].talents.masteryNodes[n.id]=n.maxRank;enemy();for(let i=0;i<3;i++)cast(i);cast('ult');tick(2500);check(k+' max talent stability',Number.isFinite(player.hp)&&portadorObjects.filter(o=>o.owner===player&&o.life>0).length<=8);resetRunTransients();check(k+' reset clears constructs',portadorObjects.length===0);
 }
 start('vesper');let e=enemy();for(let i=0;i<10;i++)damageEnemy(e,1,{src:player,fromBasic:true});check('Vesper marks cap',exMark(player,e).n===3);cast(2);check('Vesper consumes marks',exMark(player,e).n===0);exMark(player,e,3);tick(5100);check('marks expire',exMark(player,e).n===0);const h=heroes[1];exMark(player,e,2);exMark(h,e,1);check('marks separated by owner',exMark(player,e).n===2&&exMark(h,e).n===1);
 start('vesper');const crowd=Array.from({length:20},()=>enemy(20));player.basicCd=0;triggerBasic(player);check('melee basic max 12 victims',crowd.filter(e=>e.hp<1e7).length<=12);
 start('nahir');cast('ult');check('Nahir three reflections',exOwned(player,'reflection').length===3);tick(6100);check('Nahir reflections expire',exOwned(player,'reflection').length===0);
 start('baltra');for(let i=0;i<10;i++){player.invulnTimer=0;damageHero(player,1,{x:player.x+50,y:player.y,type:'esqueleto'});tick(510);}check('Baltra vibration cap',exState(player).vibration===5);cast(0);check('Baltra consumes vibration',exState(player).vibration===0);
 start('maura');e=enemy();for(let i=0;i<10;i++){damageEnemy(e,1,{src:player,fromBasic:true});tick(510);}check('Maura seed cap',exState(player).seeds===5);player.hp=player.maxHp*.5;const hp=player.hp;cast(2);check('Maura heal capped',player.hp>hp&&player.hp<=hp+player.maxHp*.050001&&exState(player).seeds===0);start('maura');e=enemy();cast(1);tick(4100);const after=e.hp;tick(4100);check('bark bursts once',after<1e7&&e.hp===after);
 start('dariel');cast(0);cast(0);check('Dariel repeat grants no note',exState(player).notes===1);cast(1);cast(0);check('Dariel three notes',exState(player).notes===3);cast(2);check('Dariel spends notes',exState(player).notes===0);cast(1);const shield=player.shield;cast(1);check('shield does not stack',player.shield===shield);
 start('orsa');e=enemy();cast(1);for(let i=0;i<5;i++)damageEnemy(e,1,{src:player,fromBasic:true});check('Orsa shots limited',exState(player).shots===0&&exMark(player,e).n===3);cast(2);check('Orsa consumes charges',exMark(player,e).n===0);
 start('tibor');for(let i=0;i<8;i++)cast(0);check('Tibor single cloud',exOwned(player,'swarm').length===1);tick(650);check('Tibor spends colony',exState(player).colony<100);cast(1);tick(10000);check('Tibor restores colony capped',exState(player).colony===100&&!exOwned(player,'swarm').length);
 start('zahra');for(let i=0;i<4;i++)cast(0);check('Zahra overheats',exState(player).recoverUntil>runElapsedMs);player.cds=[0,0,0];player.energy=110;const energy=player.energy;useSkill(0);check('Zahra recovery blocks spend',player.energy===energy);cast(1);check('Zahra quench resets heat',exState(player).heat===0);
 start('renko');for(let i=0;i<8;i++)cast(0);check('Renko soil cap',exOwned(player,'soil').length===3);cast(2);check('Renko consumes soil',exOwned(player,'soil').length===0);
 start('sira');for(let i=0;i<20;i++){player.x+=17;tick(50);}check('Sira route max 12',exRoute(player).length===12);const x=player.x;cast(1);check('Sira retrace bounded',x-player.x>0&&x-player.x<=200&&exRoute(player).length===0);tick(50);player.x+=100;tick(50);check('Sira teleport breaks route',exRoute(player).length===1);cast(2);check('Sira erase clears',exRoute(player).length===0);
 start('vesper');const oldResolve=resolveWallCollision,wall=player.x+40,from=player.x;resolveWallCollision=q=>{oldResolve(q);if(q.x>wall&&q.x<wall+20)q.x=wall;};cast(1);resolveWallCollision=oldResolve;check('dash stops at thin wall',player.x<=wall&&player.x>from);
 for(const k of Object.keys(EXPEDITION))for(const arena of ['ciudad','fortaleza','bosque','micelial','hielo','acuatica','laberinto','abismo','minas','infernal']){start(k,arena,20);enemy();for(let i=0;i<3;i++)cast(i);cast('ult');for(let i=0;i<10;i++)update(33);check(k+' arena '+arena,Number.isFinite(player.hp)&&Number.isFinite(player.x)&&portadorObjects.length<=48);}
 start('nahir');cast('ult');_netHeroIdx=new Map(heroes.map((h,i)=>[h,i]));netMatch={snapN:0,last:{},lastG:{},lastH:[{},{},{},{}]};const snap=netBuildSnapshot(true,true);check('snapshot preserves construct owner',snap.c.portadorObjects.u.every(([id,o])=>o.owner.$h===0));check('bounded serializable snapshot',JSON.stringify(snap).length<300000);netMatch=null;setState('paused');return out;
 });fs.writeFileSync('docs/expedition/functional-results.json',JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,failed:checks.filter(c=>!c.ok),errors}));if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
