'use strict';
const {chromium}=require('playwright'),{spawn}=require('node:child_process'),fs=require('node:fs');
const relay=spawn('node',['server/relay.js'],{env:{...process.env,PORT:'8810',DATA_DIR:'/tmp/expedition-relay-data',ALLOWED_ORIGINS:'http://127.0.0.1:8806'},stdio:'ignore'});
(async()=>{let b;try{await new Promise(r=>setTimeout(r,600));b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||chromium.executablePath(),args:['--no-sandbox']});const checks=[],errors=[],keys=Object.keys(require('../../js/champions/expedition/catalog'));
 for(let n=0;n<keys.length;n++){const host=keys[(n+1)%keys.length],guest=keys[n],a=await (await b.newContext()).newPage(),g=await (await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true})).newPage();
  for(const [p,c,reserve] of [[a,host,'tanque'],[g,guest,'mago']]){p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8806/?server=ws%3A%2F%2F127.0.0.1%3A8810');await p.waitForFunction(()=>typeof CHAMPION_ENTRY_BALANCE!=='undefined');await p.evaluate(([c,reserve])=>{save.starterChosen=true;for(const k in save.champions){save.champions[k].unlocked=true;save.champions[k].level=20;}selectedClass=c;save.duoReserve=reserve;currentArena='bosque';setState('prep');},[c,reserve]);}
  await a.evaluate(async()=>netCreateRoom(currentArena,selectedClass,20));const code=await a.evaluate(()=>net.code);await g.evaluate(async code=>netJoinRoom(code,selectedClass,20),code);await a.waitForFunction(()=>netHumanCount()===2);await g.evaluate(()=>netSendLoadout(true));await a.waitForFunction(()=>netDuoLoadoutValid(1));await a.evaluate(()=>netHostStartGame());await g.waitForFunction(()=>netMatch?.role==='guest'&&state==='playing');
  await a.evaluate(()=>{runLevel=ULT_MIN_ARENA_LEVEL;enemies=[];for(let j=0;j<6;j++){const e=spawnEnemy('esqueleto');Object.assign(e,{x:heroes[1].x+40+j*5,y:heroes[1].y,hp:1e7,maxHp:1e7,dmg:0,speed:0});}setInterval(()=>{spawnTimer=1e9;levelTimer=0;arenaHazardTimer=1e9;},50);});
  for(let i=0;i<3;i++){await g.evaluate(i=>useSkill(i,{x:player.x+60,y:player.y,dx:1,dy:0}),i);await g.waitForTimeout(250);}
  await a.evaluate(()=>{heroes[1].ultCharge=heroes[1].ultMax;heroes[1].ultCd=0;});await g.waitForTimeout(250);await g.evaluate(()=>useUltimate());await g.waitForTimeout(500);
  const rh=await a.evaluate(()=>({k:heroes[1].classKey,casts:heroes[1].stats.skillCasts,objects:portadorObjects.filter(o=>o.ex).map(o=>({id:o.id,owner:heroes.indexOf(o.owner),kind:o.kind})),hp:heroes[1].hp})),rg=await g.evaluate(()=>({k:player.classKey,objects:portadorObjects.filter(o=>o.ex).map(o=>({id:o.id,owner:heroes.indexOf(o.owner),kind:o.kind})),hp:player.hp}));
  const owned=rh.objects.filter(o=>o.owner===1),ok=rh.k===guest&&rg.k===guest&&rh.casts>=4&&Number.isFinite(rh.hp)&&Number.isFinite(rg.hp)&&owned.length>0&&owned.every(o=>rg.objects.some(q=>q.id===o.id&&q.owner===1&&q.kind===o.kind));checks.push({host,guest,ok,rh,rg});console.log(JSON.stringify({host,guest,ok}));await a.context().close();await g.context().close();
 }
 fs.writeFileSync('docs/expedition/online-results.json',JSON.stringify({checks,errors},null,2));if(errors.length||checks.some(c=>!c.ok))process.exitCode=1;
 }finally{if(b)await b.close();relay.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
