'use strict';
const fs=require('node:fs'),C=require('../../js/champions/expedition/catalog'),{scaffold,validate}=require('../factory/contracts');
const ref=JSON.parse(fs.readFileSync('docs/balance/champion-entry-reference.json')),read=p=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null;
const gate=read('docs/expedition/entry-gate-results.json'),functional=read('docs/expedition/functional-results.json'),online=read('docs/expedition/online-results.json'),perf=read('docs/expedition/performance-results.json');
const manifests=[];
let md=`# La Horda — Expedición de los Diez\n\nPropuesta completa y taller de prototipos · 3 de octubre de 2026.\n\nBase revisada: main 965a4504fb44ca81438fe8e31b63ca445c7bb008. Guías aplicadas: AGENTS, Balance de Campeones, referencia por rol, Art Bible, Lore Bible y Production Bibles.\n\n## Estado real\n\nDiez historias originales; diez pasivas; diez básicos; treinta habilidades y diez definitivas implementadas en un taller aislado; tres ramas de talentos por candidato; diez sets de cuatro piezas; veinte diseños de skins con historia propia y diez cromas. Las apariencias son especificaciones de producción: **no hay atlas nuevos aprobados**. El taller usa siluetas prestadas claramente rotuladas, y no se registra en el index de producción.\n\nEl taller no equivale a diez campeones terminados para la Alpha. Falta producir y revisar sprites/animaciones/previews, VFX y SFX de identidad, y la entrega persistente de cosméticos de Set. No se inventan archivos ni aprobaciones para hacer pasar el contrato.\n\n## Reglas conservadas\n\nLa Horda corrompe y no puede destruirse. No se agregan Guardianes antiguos, cristales ni cambios al orden de campaña. Las nuevas biografías son propuestas compatibles; no reescriben el canon. La sombra de Vesper no prueba una cura; el reflejo de Nahir no predice realmente el futuro. Baltra conoce el mar después de que aparece en la campaña.\n\nCada campeón tiene una herramienta multiblanco. Máximo 12 afectados por evento directo, ocho objetos propios y 48 objetos del sistema compartido. Las zonas caducan; los pulsos de definitivas tienen cantidad fija aun al ampliar duración. Las marcas pertenecen a cada jugador, expiran y no viajan como referencias inválidas. Desplazamientos comprobados por pasos contra geometría. Jefes sin empuje/aturdimiento, freno máximo 12%. Escudos no acumulables del mismo efecto; curación acotada; efectos cancelados al morir, fusionarse o reiniciar.\n\nLos valores de entrada pasan por el normalizador antes de jugar. knownChampions y las medias aprobadas no se modifican. Pasar el techo de admisión no demuestra equivalencia de utilidad, supervivencia, curación o daño en todas las builds.\n\n## Validación de esta reconstrucción\n\n`;
if(functional)md+=`- Funcional: ${functional.checks.length} comprobaciones; ${functional.checks.filter(c=>!c.ok).length} fallos; ${functional.errors.length} errores. Incluye 100 cruces campeón/arena, niveles iniciales, límites, talentos máximos, sets, control, muerte/reset y serialización. [JSON](functional-results.json).\n`;
if(gate)md+=`- Gate: ${gate.runs.length} simulaciones de 150 s; ${gate.violations.length} infracciones y ${gate.errors.length} errores. [JSON](entry-gate-results.json).\n`;
if(online)md+=`- Cooperativo: ${online.checks.length} combinaciones entre host e invitado; ${online.checks.filter(c=>!c.ok).length} fallos y ${online.errors.length} errores. Relay real local; cada candidato envía 3 habilidades + definitiva y replica entidades con dueño correcto. [JSON](online-results.json). No mide Internet público ni cuatro teléfonos físicos.\n`;
if(fs.existsSync('docs/expedition/audio-results.txt'))md+='- Audio: suite del motor existente (no diez identidades sonoras nuevas); ver [registro](audio-results.txt). La escucha humana y firmas propias siguen pendientes.\n';
if(perf)md+=`- Performance de escritorio: ${perf.frames} cuadros; p95 ${perf.p95.toFixed(2)} ms; ${perf.over33Pct.toFixed(2)}% por encima de 33,4 ms. Viewport móvil en Chromium/Linux, no iPhone físico. [JSON](performance-results.json).\n`;
md+='\n## Comparación de entrada\n\nDaño registrado por jugador en Bosque, nivel 20, tres semillas oficiales, 150 s. La referencia es histórica: diferencias del motor y autopiloto impiden tratarla como una medida de equilibrio actual. Los resultados anteriores a la interrupción no se reutilizan como evidencia.\n\n| Campeón | Rol | HP / daño / defensa | Velocidad / básico ms | Daño medio | % de referencia | Con vida |\n|---|---|---|---|---:|---:|---:|\n';
for(const [k,p] of Object.entries(C)){const runs=gate?.runs.filter(r=>r.key===k)||[],mean=runs.length?runs.reduce((s,r)=>s+r.damage,0)/runs.length:0;md+=`| ${p.name} | ${p.role} | ${p.stats[0]} / ${p.stats[1]} / ${p.stats[2]*100}% | ${p.stats[3]} / ${p.stats[5]} | ${runs.length?Math.round(mean):'Pendiente'} | ${runs.length?Math.round(mean/ref.roles[p.role].simulation.meanDamage150s*100)+'%':'—'} | ${runs.filter(r=>r.alive).length}/${runs.length} |\n`;}
md+='\nEstadísticas de la tabla: propuesta previa al normalizador; los valores finales y ajustes figuran en entries del JSON del gate. Daño bajo también requiere revisión: este gate solo bloquea excesos, errores y falta de lanzamientos.\n\n## Fichas\n';
for(const [k,p] of Object.entries(C)){
 const m=scaffold(k);Object.assign(m,{name:p.name,title:p.title,role:p.role,fantasy:p.fantasy,lore:p.history,personality:p.voices[0],silhouette:p.silhouette,stats:{hp:p.stats[0],damage:p.stats[1],defense:p.stats[2],speed:p.stats[3]},budgets:{particles:64,summons:8,audioVoices:4}});
 const ability=(a,i)=>({id:a[1],description:a[8],cooldownMs:a[3],energyCost:a[2],range:a[4],radius:a[5],durationMs:a[6],damageMultiplier:a[7],maxTargets:12,hordeMechanism:a[8],anticipation:'Taller: destello de lanzamiento del motor. Producción: pose dedicada y aviso espacial fiel antes del impacto.',execution:a[8],impact:'Aplicación por anfitrión a blancos vivos; máximo 12 por evento. Escalado del motor y resistencias de jefes.',feedback:'Contorno del área persistente, impacto y contadores. Arte final pendiente.',vfx:'Prototipo geométrico legible; requiere firma visual propia aprobada.',sfx:'Reutiliza explícitamente cast/ult del motor; diseño y escucha de identidad pendientes.'});
 m.kit.basic={id:'basic',description:'Ataque con '+p.weapon+(p.stats[6]?', proyectil a distancia.':', barrido cuerpo a cuerpo (máximo 12).'),cooldownMs:p.stats[5],maxTargets:p.stats[6]?1:12,hordeMechanism:p.stats[6]?'El kit aporta área.':'Barrido de hasta 12 blancos.',anticipation:'Pose básica compartida del motor; animación propia pendiente.',execution:'Ataque básico del motor con daño, alcance y recarga de la clase.',impact:'Daño real y pasiva al impactar, no al pulsar el botón.',feedback:'Impacto y número de daño del motor.',vfx:'Firma de prototipo; asset propio pendiente.',sfx:'Básico existente del motor, reutilizado explícitamente.'};m.kit.skills=p.skills.slice(0,3).map(ability);m.kit.ultimate=ability(p.skills[3]);m.kit.passive={name:p.passive[0],description:p.passive[1]};
 for(const key of ['runtime','talents','mastery','set','kitTest','codex'])m.integration[key]=key==='runtime'?'js/champions/expedition/runtime.js':key==='kitTest'?'tools/expedition/functional.js':'js/champions/expedition/register.js';
 m.art.productionPrompt=`Diseñar ${p.name}, ${p.title}. ${p.silhouette} Referencia obligatoria assets/sprites/champions/tanque/atlas.png. Pixel art dark fantasy chibi, cabeza 40–45%, contorno oscuro 1 px, 2–3 tonos, 4–6 colores, alfa binario. Abajo, derecha, arriba e izquierda por espejo. Misma ropa, arma, proporciones y ancla de pies en idle, walk, attack, cast, hit, death y ultimate. No convertir ilustración HD en pixel art. No texto dentro del atlas. Primero aprobar turnaround; luego animar y comparar a escala de juego.`;
 m.cosmetics=p.skins.map((a,i)=>({id:k+(i?'_set':'_skin'),champion:k,name:a[0],type:i?'set':'skin',rarity:'epic',tagline:a[1],lore:a[2],visualTheme:a[1],visualChanges:['clothing','accessory','secondarySilhouette'],unlockSource:i?'Propuesta: colección persistente del Set '+p.setName+'; grant aún no implementado.':'Propuesta: catálogo Alpha, disponible para pruebas al aprobar arte.',collection:'Expedición de los Diez',vfxProfile:'Misma geometría y duración del original; variación cosmética pendiente.',sfxProfile:'Reutiliza original sin alterar señales.',preview:'',availability:'alpha-test',premiumPrice:null,currency:null}));m.cosmetics.push({id:k+'_croma',champion:k,name:p.name+' — Ceniza del Alba',type:'croma',rarity:'rare',tagline:'Marfil, gris ceniza y acento del original.',lore:'El polvo del viaje cubre la ropa antes de que llegue la primera luz.',visualTheme:'Solo paleta; conserva vestuario y accesorios.',visualChanges:['palette'],unlockSource:'Propuesta: pruebas Alpha tras aprobación visual.',collection:'Expedición de los Diez',vfxProfile:'Original',sfxProfile:'Original',preview:'',availability:'alpha-test',premiumPrice:null,currency:null});
 m.set={name:p.setName,sourceArena:p.arena,pieces:['arma','casco','pechera','botas'],rewardCosmetic:k+'_set',rewardGrantsPower:false,bonuses:{2:'+5% HP',3:'+4% daño de habilidades',4:'−4% recargas'},farmStatus:'Diseñado: repetir arena y jefe. Drop y grant de skin pendientes de integración final.'};
 m.evidence={reference:'docs/expedition/reference-results.txt',balance:gate?'docs/expedition/entry-gate-results.json':'',visuals:'',audio:fs.existsSync('docs/expedition/audio-results.txt')?'docs/expedition/audio-results.txt':'',multiplayer:online?'docs/expedition/online-results.json':'',performance:perf?'docs/expedition/performance-results.json':''};
 const errors=validate(m);manifests.push({id:k,status:errors.length?'INCOMPLETE':'STRUCTURAL_PASS',errors});fs.writeFileSync('docs/expedition/manifests/'+k+'.json',JSON.stringify(m,null,2));
 md+=`\n### ${p.name} — ${p.title}\n\n**${p.role}.** ${p.fantasy}\n\n${p.history}\n\n**Silueta:** ${p.silhouette}\n\n**Debilidad:** ${p.weakness}\n\n**Básico:** ${p.weapon}; ${p.stats[6]?'a distancia':'cuerpo a cuerpo'}, alcance ${p.stats[4]}, recarga ${p.stats[5]} ms.\n\n**Pasiva — ${p.passive[0]}:** ${p.passive[1]}\n\n| Poder | Coste | CD | Daño × | Alcance / radio | Duración base | Efecto |\n|---|---:|---:|---:|---|---:|---|\n`;
 p.skills.forEach((s,i)=>md+=`| ${i===3?'★ ':''}${s[0]} | ${s[2]} | ${s[3]/1000} s | ${s[7]} | ${s[4]} / ${s[5]} | ${s[6]/1000} s | ${s[8]} |\n`);
 md+=`\nDaño × multiplica el daño de habilidad calculado por el motor; en efectos por pulsos es **por pulso**, no daño total. El radio/alcance efectivo respeta techos del runtime aun con talentos.\n\n**Talentos y maestría:** tres ramas, una por habilidad: +5% al efecto por rango, +5% área (duración para postura) y −3% CD, tres rangos cada una. Los poderes sin daño aumentan duración (reflejo/postura/montículo) o distancia (retroceso). Maestría de rama añade 10% al efecto correspondiente; miniárbol dos rangos de +5% al efecto y +5% poder de definitiva. Son árboles de prototipo, pendientes de especializaciones artísticas/UI.\n\n**Set — ${p.setName}:** arma, casco, pechera, botas. 2 piezas +5% vida; 3 +4% daño de habilidades; 4 −4% recargas. Fuente propuesta: ${p.arena}. Completar la colección otorgaría la segunda skin; falta integrar el grant persistente, no se simula como obtenido.\n\n**Apariencias:**\n\n`;
 p.skins.forEach((s,i)=>md+=`- **${s[0]}**${i?' (skin de Set)':''}: ${s[1]} ${s[2]}\n`);md+=`- **Ceniza del Alba (croma):** marfil y ceniza, sin cambios de ropa; se etiqueta croma.\n\n**Voces:** elección «${p.voices[0]}»; victoria «${p.voices[1]}»; caída «${p.voices[2]}».\n\n**Contrato:** [${k}.json](manifests/${k}.json).\n`;
}
md+='\n## Cierre de producción pendiente\n\n1. Producir 10 atlas originales y 20 variantes de vestuario, animaciones y previews. Aplicar el visual gate con referencia Tanque; conservar INCOMPLETE hasta PASS. Los prompts completos están en cada contrato.\n2. Crear anticipaciones, impactos y firmas visuales/sonoras propias; comprobar lectura con partículas mínimas y audio apagado. Escucha humana, control de mezcla y revisión táctil de 667×375.\n3. Conectar drops a las arenas propuestas y grant de skin de Set por colección persistente, idempotente y sin bonus cosmético.\n4. Balance ampliado: diez semillas/rol, Bosque/Minas/Infernal, solo y cuatro jugadores, nivel inicial/20/40, builds completas y curación/daño recibido/tiempo caído. No ajustar por DPS solamente.\n5. Medir iPhone real antes de aprobar el piso móvil. Solo después registrar módulos antes del normalizador en index y pasar gates sobre el candidato final.\n\n## Repetir el taller\n\nNo utiliza la web publicada. Requiere Node, Python, Playwright y Chromium; relay usa el lockfile de server. El puerto propio separa localStorage de la web de producción. Usar perfiles de prueba; no iniciar cuentas reales.\n\n```sh\nnode tools/expedition/server.js\n# En otra terminal, desde la raíz; CHROMIUM_PATH es opcional si Playwright tiene browser instalado:\nnode tools/balance/check-entry-reference.js > docs/expedition/reference-results.txt\nnode tools/expedition/functional.js\nENTRY_BASE_URL=http://127.0.0.1:8806 node tools/balance/entry-gate.js\ncp docs/balance/entry-gate-results.json docs/expedition/entry-gate-results.json\n# Restaurar el informe del roster de producción, no sustituirlo con el taller:\ngit restore docs/balance/entry-gate-results.json\nnpm --prefix server ci --ignore-scripts\nnode tools/expedition/online.js\nnode tools/expedition/performance.js\nnode tools/expedition/production.js\n```\n\n`production.js` conserva los manifiestos INCOMPLETE por falta de assets/evidencia visual. No rebaja el contrato ni registra automáticamente campeones.\n';
fs.writeFileSync('docs/expedition/README.md',md);fs.writeFileSync('docs/expedition/contract-results.json',JSON.stringify(manifests,null,2));console.log(JSON.stringify({champions:manifests.length,statuses:manifests.map(x=>[x.id,x.status])}));
