'use strict';
const fs=require('node:fs'),C=require('../../js/champions/expedition/catalog'),{scaffold,validate}=require('../factory/contracts');
const ref=JSON.parse(fs.readFileSync('docs/balance/champion-entry-reference.json')),read=p=>fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):null;
const gate=read('docs/expedition/entry-gate-results.json'),functional=read('docs/expedition/functional-results.json'),online=read('docs/expedition/online-results.json'),perf=read('docs/expedition/performance-results.json');
const A=require('../../js/champions/expedition/art-data.json'),crypto=require('node:crypto');
const manifests=[];
let md=`# La Horda — Expedición de los Diez\n\nDiez campeones integrados para la Alpha, con 30 habilidades, 10 definitivas, pasivas, historias, talentos, maestrías, 10 sets, 20 skins de vestuario y 10 cromas.\n\nBase: main bcebd0f. Referencias de balance y knownChampions conservadas. Registro anterior al normalizador. Los campeones nuevos empiezan bloqueados a nivel 1 y se compran con oro mediante la tienda existente; no se reinicia el progreso de cuentas.\n\n## Reglas y límites\n\nLa Horda corrompe y no puede destruirse. No se agregan Guardianes antiguos ni cristales. Las historias conservan el orden de campaña. Máximo 12 blancos por evento, 8 objetos por dueño, pulsos finitos, marcas por jugador, caducidad y limpieza al morir. Desplazamientos prueban la geometría en pasos de 6 unidades. Los jefes resisten desplazamiento/aturdimiento y su freno no supera 12%. Los cosméticos no alteran daño, estadísticas, hitbox ni recargas.\n\n## Evidencia\n\n`;
if(functional)md+=`- Funcional: ${functional.checks.length} comprobaciones; ${functional.checks.filter(c=>!c.ok).length} fallos; ${functional.errors.length} errores. Incluye 100 cruces campeón/arena, niveles iniciales, límites, talentos máximos, sets, control, muerte/reset y serialización. [JSON](functional-results.json).\n`;
if(gate)md+=`- Gate: ${gate.runs.length} simulaciones de 150 s; ${gate.violations.length} infracciones y ${gate.errors.length} errores. [JSON](entry-gate-results.json).\n`;
if(online)md+=`- Cooperativo: ${online.checks.length} combinaciones entre host e invitado; ${online.checks.filter(c=>!c.ok).length} fallos y ${online.errors.length} errores. Relay real local; cada candidato envía 3 habilidades + definitiva y replica entidades con dueño correcto. [JSON](online-results.json). No mide Internet público ni cuatro teléfonos físicos.\n`;
if(fs.existsSync('docs/expedition/audio-results.txt'))md+='- Audio: suite de mezcla del motor y acentos sintetizados propios en audio.js; ver [registro](audio-results.txt). La medición offline no sustituye una escucha humana de fatiga.\n';
if(perf)md+=`- Performance de escritorio: ${perf.frames} cuadros; p95 ${perf.p95.toFixed(2)} ms; ${perf.over33Pct.toFixed(2)}% por encima de 33,4 ms. Viewport móvil en Chromium/Linux, no iPhone físico. [JSON](performance-results.json).\n`;
md+='\n## Comparación de entrada\n\nDaño registrado por jugador en Bosque, nivel 20, tres semillas oficiales, 150 s. La referencia es histórica: diferencias del motor y autopiloto impiden tratarla como una medida de equilibrio actual. Los resultados anteriores a la interrupción no se reutilizan como evidencia.\n\n| Campeón | Rol | HP / daño / defensa | Velocidad / básico ms | Daño medio | % de referencia | Con vida |\n|---|---|---|---|---:|---:|---:|\n';
for(const [k,p] of Object.entries(C)){const runs=gate?.runs.filter(r=>r.key===k)||[],mean=runs.length?runs.reduce((s,r)=>s+r.damage,0)/runs.length:0;md+=`| ${p.name} | ${p.role} | ${p.stats[0]} / ${p.stats[1]} / ${p.stats[2]*100}% | ${p.stats[3]} / ${p.stats[5]} | ${runs.length?Math.round(mean):'Pendiente'} | ${runs.length?Math.round(mean/ref.roles[p.role].simulation.meanDamage150s*100)+'%':'—'} | ${runs.filter(r=>r.alive).length}/${runs.length} |\n`;}
md+='\nEstadísticas de la tabla: propuesta previa al normalizador; los valores finales y ajustes figuran en entries del JSON del gate. Daño bajo también requiere revisión: este gate solo bloquea excesos, errores y falta de lanzamientos.\n\n## Fichas\n';
for(const [k,p] of Object.entries(C)){
 const m=scaffold(k);Object.assign(m,{name:p.name,title:p.title,role:p.role,fantasy:p.fantasy,lore:p.history,personality:p.voices[0],silhouette:p.silhouette,stats:{hp:p.stats[0],damage:p.stats[1],defense:p.stats[2],speed:p.stats[3]},budgets:{particles:64,summons:8,audioVoices:4}});
 const ability=(a,i)=>({id:a[1],description:a[8],cooldownMs:a[3],energyCost:a[2],range:a[4],radius:a[5],durationMs:a[6],damageMultiplier:a[7],maxTargets:12,hordeMechanism:a[8],anticipation:'Pose de lanzamiento y destello del motor; básico/habilidad de respuesta inmediata. Zonas persistentes muestran su perímetro real.',execution:a[8],impact:'Aplicación por anfitrión a blancos vivos; máximo 12 por evento. Escalado del motor y resistencias de jefes.',feedback:'Perímetro persistente, glifo del campeón, impacto, contadores y pose de recuperación.',vfx:'Glifo propio, dirección y perímetro; render.js. No depende de partículas decorativas.',sfx:'Acento sintetizado ex_<campeón>_cast/ult, mezcla y mute del motor; audio.js.'});
 m.kit.basic={id:'basic',description:'Ataque con '+p.weapon+(p.stats[6]?', proyectil a distancia.':', barrido cuerpo a cuerpo (máximo 12).'),cooldownMs:p.stats[5],maxTargets:p.stats[6]?1:12,hordeMechanism:p.stats[6]?'El kit aporta área.':'Barrido de hasta 12 blancos.',anticipation:'Secuencia propia de ataque por dirección, con anticipación corta.',execution:'Ataque básico del motor con daño, alcance y recarga de la clase.',impact:'Daño real y pasiva al impactar, no al pulsar el botón.',feedback:'Impacto y número de daño del motor.',vfx:'Atlas propio y feedback de impacto del motor.',sfx:'Básico existente del motor, reutilizado explícitamente.'};m.kit.skills=p.skills.slice(0,3).map(ability);m.kit.ultimate=ability(p.skills[3]);m.kit.passive={name:p.passive[0],description:p.passive[1]};
 for(const key of ['runtime','talents','mastery','set','kitTest','codex'])m.integration[key]=key==='runtime'?'js/champions/expedition/runtime.js':key==='kitTest'?'tools/expedition/functional.js':'js/champions/expedition/register.js';
 m.art.productionPrompt=`Diseñar ${p.name}, ${p.title}. ${p.silhouette} Referencia obligatoria assets/sprites/champions/tanque/atlas.png. Pixel art dark fantasy chibi, cabeza 40–45%, contorno oscuro 1 px, 2–3 tonos, 4–6 colores, alfa binario. Abajo, derecha, arriba e izquierda por espejo. Misma ropa, arma, proporciones y ancla de pies en idle, walk, attack, cast, hit, death y ultimate. No convertir ilustración HD en pixel art. No texto dentro del atlas. Primero aprobar turnaround; luego animar y comparar a escala de juego.`;
 const art=A[k];Object.assign(m.art,{atlas:art.src,preview:art.preview,directions:4,frameWidth:112,frameHeight:112,sha256:crypto.createHash('sha256').update(fs.readFileSync(art.src)).digest('hex'),animations:{idle:1,walk:4,attack:4,cast:4,hit:1,death:4,ultimate:4},review:{status:'PASS',reviewer:'Codex — inspección visual frente a Tanque y revisión técnica',evidence:'docs/expedition/visual-review.json'}});
 m.cosmetics=p.skins.map((a,i)=>({id:k+(i?'_set':'_skin'),champion:k,name:a[0],type:i?'set':'skin',rarity:'epic',tagline:a[1],lore:a[2],visualTheme:a[1],visualChanges:['clothing','accessory','secondarySilhouette'],unlockSource:i?'Colección persistente del Set '+p.setName+'; se conserva al vender o desequipar.':'Tienda Alpha: oro del juego, disponible para pruebas.',collection:'Expedición de los Diez',vfxProfile:'Geometría, duración y firma original; sin ventaja jugable.',sfxProfile:'Reutiliza original sin alterar señales.',preview:A[k+(i?'_set':'_skin')].preview,availability:'alpha-test',premiumPrice:null,currency:null}));m.cosmetics.push({id:k+'_croma',champion:k,name:p.name+' — Ceniza del Alba',type:'croma',rarity:'rare',tagline:'Marfil, gris ceniza y acento del original.',lore:'El polvo del viaje cubre la ropa antes de que llegue la primera luz.',visualTheme:'Solo paleta; conserva vestuario y accesorios.',visualChanges:['palette'],unlockSource:'Tienda Alpha: oro del juego.',collection:'Expedición de los Diez',vfxProfile:'Original',sfxProfile:'Original',preview:'assets/sprites/champions/'+k+'/croma-preview.png',availability:'alpha-test',premiumPrice:null,currency:null});
 m.set={name:p.setName,sourceArena:p.arena,pieces:['arma','casco','pechera','botas'],rewardCosmetic:k+'_set',rewardGrantsPower:false,bonuses:{2:'+5% HP',3:'+4% daño de habilidades',4:'−4% recargas'},farmStatus:'Repetir arena y jefe. Peso doble en su arena temática; también disponible en otros mapas y tienda Alpha. Grant persistente por colección completa.'};
 m.evidence={reference:'docs/expedition/reference-results.txt',balance:gate?'docs/expedition/entry-gate-results.json':'',visuals:'docs/expedition/visual-review.json',audio:fs.existsSync('docs/expedition/audio-results.txt')?'docs/expedition/audio-results.txt':'',multiplayer:online?'docs/expedition/online-results.json':'',performance:perf?'docs/expedition/performance-results.json':''};
 const errors=validate(m);manifests.push({id:k,status:errors.length?'INCOMPLETE':'STRUCTURAL_PASS',errors});fs.writeFileSync('docs/expedition/manifests/'+k+'.json',JSON.stringify(m,null,2));
 md+=`\n### ${p.name} — ${p.title}\n\n**${p.role}.** ${p.fantasy}\n\n${p.history}\n\n**Silueta:** ${p.silhouette}\n\n**Debilidad:** ${p.weakness}\n\n**Básico:** ${p.weapon}; ${p.stats[6]?'a distancia':'cuerpo a cuerpo'}, alcance ${p.stats[4]}, recarga ${p.stats[5]} ms.\n\n**Pasiva — ${p.passive[0]}:** ${p.passive[1]}\n\n| Poder | Coste | CD | Daño × | Alcance / radio | Duración base | Efecto |\n|---|---:|---:|---:|---|---:|---|\n`;
 p.skills.forEach((s,i)=>md+=`| ${i===3?'★ ':''}${s[0]} | ${s[2]} | ${s[3]/1000} s | ${s[7]} | ${s[4]} / ${s[5]} | ${s[6]/1000} s | ${s[8]} |\n`);
 md+=`\nDaño × multiplica el daño de habilidad calculado por el motor; en efectos por pulsos es **por pulso**, no daño total. El radio/alcance efectivo respeta techos del runtime aun con talentos.\n\n**Talentos y maestría:** tres ramas, una por habilidad: +5% al efecto por rango, +5% área (duración para postura) y −3% CD, tres rangos cada una. Los poderes sin daño aumentan duración (reflejo/postura/montículo) o distancia (retroceso). Maestría de rama añade 10% al efecto correspondiente; miniárbol dos rangos de +5% al efecto y +5% poder de definitiva. Árboles registrados en la UI de talentos existente.\n\n**Set — ${p.setName}:** arma, casco, pechera, botas. 2 piezas +5% vida; 3 +4% daño de habilidades; 4 −4% recargas. Arena con peso doble de drop: ${p.arena}. Completar la colección desbloquea permanentemente la segunda skin, sin poder adicional.\n\n**Apariencias:**\n\n`;
 p.skins.forEach((s,i)=>md+=`- **${s[0]}**${i?' (skin de Set)':''}: ${s[1]} ${s[2]}\n`);md+=`- **Ceniza del Alba (croma):** marfil y ceniza, sin cambios de ropa; se etiqueta croma.\n\n**Voces:** elección «${p.voices[0]}»; victoria «${p.voices[1]}»; caída «${p.voices[2]}».\n\n**Contrato:** [${k}.json](manifests/${k}.json).\n`;
}
md+='\n## Arte y revisión\n\n30 atlas originales con cuatro direcciones (izquierda por espejo), ataques direccionales, cast, hit, muerte y definitiva. Reutilización explícita de poses coherentes: idle/hit y cast frontal en otras direcciones; Vesper Corte reutiliza cast en ultimate. Los metadatos enumeran los índices reales. Cromas calculadas por el renderizador de paletas existente. Ver [revisión visual](visual-review.json), [roster](visual-roster.png) y [pruebas cosméticas](cosmetics-results.json).\n\nLas pruebas de performance usan Chromium/Linux con viewport móvil; no certifican un iPhone físico. El gate de entrada limita excesos de daño y errores, no demuestra balance competitivo para todas las builds. La escucha humana de fatiga y pruebas públicas de red son validaciones posteriores de Alpha, no resultados inventados.\n\n## Repetir\n\n```sh\nnode tools/expedition/server.js\n# Otra terminal con Playwright/Chromium instalados\nnode tools/balance/check-entry-reference.js\nnode tools/expedition/functional.js\nENTRY_BASE_URL=http://127.0.0.1:8806 node tools/balance/entry-gate.js\nnode tools/expedition/cosmetics-test.js\nnode tools/expedition/online.js\nnode tools/expedition/performance.js\nnode tools/audio/t_audio_mix.js\nnode tools/expedition/production.js\n```\n';
fs.writeFileSync('docs/expedition/README.md',md);fs.writeFileSync('docs/expedition/contract-results.json',JSON.stringify(manifests,null,2));console.log(JSON.stringify({champions:manifests.length,statuses:manifests.map(x=>[x.id,x.status])}));
