'use strict';
const fs=require('node:fs'),C=require('../../js/champions/expedition/catalog'),A=require('../../js/champions/expedition/art-data.json');
const lines=['"use strict";','// Authored atlases; generated by tools/expedition/register-art.js.'];
for(const [id,a] of Object.entries(A)){
 const p=C[a.champ];if(!p)continue;
 if(!a.variant)lines.push(`champPackLoadAtlas(${JSON.stringify(id)},${JSON.stringify(a.src)},${JSON.stringify(a.meta)});`);
 else if(a.variant==='set'){
  lines.push(`champPackLoadAtlas(${JSON.stringify(id)},${JSON.stringify(a.src)},${JSON.stringify(a.meta)});`);
  const data={champ:a.champ,name:p.skins[1][0],src:a.preview,preview:a.preview,packs:{[a.champ]:id},preserveAuthoredArt:true,lore:p.skins[1][2],visualTheme:p.skins[1][1],tagline:p.skins[1][1],rarity:'Épica',collection:'Expedición de los Diez',sfxProfile:'Original'};
  lines.push(`SET_SKINS[${JSON.stringify('exp_'+a.champ)}]=${JSON.stringify(data)};`);
 }else if(a.variant==='skin'){
  const data={champ:a.champ,name:p.skins[0][0],price:1000,crystal:'expedition',appearanceType:'skin',rarity:'Épica',preview:a.preview,preserveAuthoredArt:true,lore:p.skins[0][2],visualTheme:p.skins[0][1],tagline:p.skins[0][1],collection:'Expedición de los Diez',files:{},authoredPacks:{[a.champ]:{src:a.src,meta:a.meta}}};
  lines.push(`CROMA_SKINS[${JSON.stringify(id)}]=${JSON.stringify(data)};`);
 }
}
fs.writeFileSync('js/champions/expedition/art.js',lines.join('\n')+'\n');
