"""Technical import of imagegen-authored poses: alpha cleanup, crop, nearest pack.
Does not paint, recolor or synthesize poses. See manifest.json for frame exclusions.
"""
from pathlib import Path
from PIL import Image
import json
import numpy as np
from scipy.ndimage import label
ROOT=Path(__file__).resolve().parents[3]
SRC=ROOT/'art-source/alpha-set-skins'
manifest=json.loads((SRC/'manifest.json').read_text())
js=['"use strict";','// Generated by tools/art/alpha_set_skins/build.py; authored art, no procedural recolor.']
report={}
for entry in manifest['skins']:
 key,sid=entry['champion'],entry['set']
 sheet=Image.open(SRC/(key+'.png')).convert('RGBA'); cells=[None]*24
 # Imagegen can drift row positions. Segment six complete silhouettes per column,
 # exactly as the existing complete_skins importer, never clip at nominal rows.
 for x in range(4):
  column=sheet.crop((x*sheet.width//4,0,(x+1)*sheet.width//4,sheet.height))
  components,n=label(np.array(column.getchannel('A'))>=128)
  sizes=np.bincount(components.ravel());sizes[0]=0
  ids=sorted(range(1,n+1),key=lambda i:sizes[i],reverse=True)[:6]
  if len(ids)!=6 or min(sizes[i] for i in ids)<10000:raise ValueError(f'{key} column {x}: six complete poses required')
  ids.sort(key=lambda i:np.where(components==i)[0].mean())
  for y,component in enumerate(ids):
   cell=column.copy();cell.putalpha(Image.fromarray(((components==component)*255).astype('uint8')))
   box=cell.getbbox()
   if box[0]<2 or box[2]>column.width-2:raise ValueError(f'{key} frame {y*4+x}: crosses column margin')
   cells[y*4+x]=cell.crop(box)
 scale=min(76/cells[0].height,86/max(c.height for c in cells),88/max(c.width for c in cells))
 atlas=Image.new('RGBA',(384,576)); bounds=[]
 for n,cell in enumerate(cells):
  cell=cell.resize((round(cell.width*scale),round(cell.height*scale)),Image.Resampling.NEAREST)
  x,y=n%4*96+(96-cell.width)//2,n//4*96+90-cell.height
  if n not in [f["index"] for f in entry["excludedFrames"]]:atlas.alpha_composite(cell,(x,y))
  bounds.append([cell.width,cell.height])
 rel=f'assets/sprites/champions/{key}/skins/{sid}';out=ROOT/rel;out.mkdir(parents=True,exist_ok=True)
 atlas.save(out/'atlas.png');atlas.crop((0,0,96,96)).save(out/'preview.png')
 ref=round(cells[0].height*scale)
 sets={}
 for direction,offset in [('down',0),('side',4),('up',8)]:
  if key=='myla':
   sets.update({f'idle_{direction}':[offset],f'walk_{direction}':[offset+1,offset,offset+2,offset],f'attack_{direction}':[offset,offset+3,offset+3],f'cast_{direction}':[offset,offset+3,offset+3],f'ultimate_{direction}':[offset+12,offset+14,offset+15],f'hit_{direction}':[offset+12],f'death_{direction}':[offset+12]})
  else:
   walk=[offset,offset+1,offset+2,offset+3] if direction!='up' else [8,9,10,9]
   sets.update({f'idle_{direction}':[offset],f'walk_{direction}':walk,f'attack_{direction}':list(range(offset+12,offset+16)),f'cast_{direction}':list(range(offset+12,offset+16)),f'ultimate_{direction}':list(range(offset+12,offset+16)),f'hit_{direction}':[offset+12],f'death_{direction}':[offset+12]})
 meta=dict(w=96,h=96,cols=4,refH=ref,anchor=.9375,fix={'left':'mirror'},sets=sets)
 pack='skin_'+sid;js.append(f'champPackLoadAtlas({json.dumps(pack)},"{rel}/atlas.png",{json.dumps(meta)});')
 packs={key:pack}
 if key=='myla':
  ultsets={}
  for direction,offset in [('down',12),('side',16),('up',20)]:
   frames=list(range(offset,offset+4)) if direction!='side' else [16,18,19,18]
   for state in ['idle','walk','attack','cast','ultimate']:ultsets[state+'_'+direction]=frames
  ultmeta=dict(meta,sets=ultsets)
  js.append(f'champPackLoadAtlas("{pack}_berrinche","{rel}/atlas.png",{json.dumps(ultmeta)});')
  packs['myla_berrinche']=pack+'_berrinche'
 definition=dict(champ=key,name=entry['name'],lore=entry['lore'],src=rel+'/preview.png',preview=rel+'/preview.png',packs=packs,preserveAuthoredArt=True,visualTheme=entry['theme'],rarity='Set')
 js.append(f'SET_SKINS[{json.dumps(sid)}]={json.dumps(definition,ensure_ascii=False)};')
 report[key]=dict(frames=24,uniformScale=scale,refH=ref,bounds=bounds,excludedFrames=entry['excludedFrames'])
# Preserve the previously shipped set recolors as selectable cromas.
for key,sid,crystal,name,legacy in [('myla','myla_arandanos','arandanos','Myla — Yogur de Arándanos','merienda_magica'),('ynara','ynara_celeste','celeste','Ynara — Guardia Celeste','santa_paciencia')]:
 out=ROOT/f'assets/sprites/champions/{key}/cromas/{sid}';out.mkdir(parents=True,exist_ok=True)
 im=Image.open(SRC/f'skin_{legacy}-legacy-croma.png').convert('RGBA');im.save(out/'atlas.png');im.crop((0,0,96,96)).save(out/'preview.png')
 rel=str(out.relative_to(ROOT));files={key:rel+'/atlas.png'}
 if key=='myla':
  Image.open(SRC/'skin_merienda_magica_berrinche-legacy-croma.png').save(out/'berrinche.png');files['myla_berrinche']=rel+'/berrinche.png'
 d=dict(champ=key,name=name,crystal=crystal,price=1500,legacySet=legacy,lore='La paleta que acompañó a '+('Myla en sus primeras meriendas entre guardianes.' if key=='myla' else 'Ynara durante las guardias del refugio.'),preview=rel+'/preview.png',files=files)
 js.append(f'CROMA_SKINS[{json.dumps(sid)}]={json.dumps(d,ensure_ascii=False)};')
(ROOT/'js/assets/alpha-set-skins-meta.js').write_text('\n'.join(js)+'\n')
(SRC/'frame-report.json').write_text(json.dumps(report,indent=2)+'\n')
print('Packed 46 approved poses from 48 authored; 2 rejected cells empty; preserved 2 legacy cromas.')
