'use strict';
/* ============================================================
   js/champions/ascension/catalog.js
   Diseño de los campeones de la expansión "Ascensión": dos Regentes Fundadores (FOUNDER) y seis
   STANDARD. Categoría, estado de publicación y adquisición viven en js/data/champion-taxonomy.js;
   este archivo no decide quién los posee.
   Formato de skills: [nombre, acción, costo, cd(ms), alcance, radio, duración(ms), multDaño, descripción, afinidad]
   Arte de personaje: PENDIENTE de encargo (docs/founders/ART_BRIEFS.md). Hasta pasar el Visual Gate
   se dibujan con el sprite de respaldo (paleta propia) y sus VFX en capas separadas (Art Bible §7).
   ============================================================ */
const ASCENSION = {
 nano_gm:{name:'Nano GM',title:'El Regente del Umbral',origin:'El umbral sobre la Arena Infernal',tagline:'Nano GM alterna Luz y Oscuridad, reescribe las reglas de la Arena y la parte en dos con su Juicio.',role:'mago',color:'#e8c56a',glow:'#fff4d6',stats:[150,15,.15,178,270,420,true],weapon:'Brazos del Umbral',arena:'infernal',
  founder:'nano',
  fantasy:'Regente que reescribe las reglas locales de la arena: la Luz decide quién resiste y la Oscuridad, quién cae.',
  silhouette:'Joven atlético de rulos oscuros; ambos brazos cubiertos de tatuajes negros que se agrietan en runas. Ala de luz y ala de sombra asimétricas, a medio materializar en reposo.',
  history:'Antes de que el Forjador partiera el Sello, alguien escribió las reglas de las Arenas: cuánto pesa un golpe, qué cuenta como victoria. Los Regentes no pelearon contra la Horda; la observaron desde el umbral donde la luz y la sombra aún no se separaban. Nano es el primero que decidió cruzar. Sus tatuajes no son adorno: son las cláusulas del pacto, grabadas en la piel para que ninguna regla se le olvide. Cuando entra en combate, la arena lo reconoce antes que los campeones.',
  passive:['Autoridad del GM','Cada habilidad tiene afinidad LUZ (protege, restaura, ordena) u OSCURIDAD (daña, debilita, ejecuta). Alternar afinidades acumula Equilibrio; con 2 de Luz y 2 de Sombra entra en FORMA DEL REGENTE (8 s): ambas afinidades a la vez, +20% daño, −15% daño recibido y más alcance.'],
  weakness:'Fuera de Equilibrio sus habilidades rinden menos; la Forma tiene recarga interna de 20 s.',
  voices:['La regla acaba de cambiar.','Partida terminada. Yo firmé el resultado.','Esto… no estaba en el reglamento…'],
  entryLine:'La luz decide quién se queda. La sombra, quién se va.',
  setName:null,
  skins:[['Regente del Eclipse Dorado','Bordes de ala en oro batido, halo de eclipse detrás de la nuca y runas de los tatuajes que arden en oro en lugar de blanco.','Cuando el primer eclipse cubrió las arenas, Nano decidió que la sombra también merecía una corona.']],
  skills:[['Sentencia Umbría','sentence',22,4600,330,30,0,4.6,'Decreto de sombra en línea: daña y SENTENCIA (+15% de daño recibido, 4 s). Comunes sentenciados con menos de 22% de vida son ejecutados.','dark'],
   ['Edicto de Luz','edict',26,8200,300,135,5000,.9,'Ley de refugio en el suelo: aliados dentro reciben escudo, −15% de daño y regeneración; enemigos dentro se frenan.','light'],
   ['Inversión','invert',20,6800,260,110,0,2.9,'Se traslada al punto elegido. Deja una runa opuesta a su última afinidad: Sombra estalla en daño; Luz cura al llegar.','swap'],
   ['Juicio del GM','judgement',0,62000,0,440,2600,6.0,'Pausa dramática, alas desplegadas y la arena dividida: aliados restaurados; comunes ejecutados o devastados; élites y jefes reciben daño masivo respetando sus mecánicas. Entra en Forma del Regente.','both']]},
 facu_gm:{name:'Facu GM',title:'El Soberano de las Mareas',origin:'La fosa bajo la Arena Acuática',tagline:'Facu GM encadena corriente, presión y oleada: el océano responde antes que sus órdenes.',role:'asesino',color:'#2fd3c6',glow:'#7ff3ff',stats:[165,15,.14,186,92,400,false],weapon:'Quilla Ceremonial',arena:'acuatica',
  founder:'facu',
  fantasy:'No usa el agua: el océano le responde. Encadena corrientes, presión y oleadas para ordenar el campo antes de que el enemigo entienda el patrón.',
  silhouette:'Joven musculoso de rulos oscuros, postura de quien lee el mar. Manto de agua viva que nace de los hombros y una corona de corrientes; empuña una Quilla Ceremonial de forma hidrodinámica.',
  history:'Las Arenas tienen fondo. Debajo del Acuático, más allá de donde el Leviatán dejó de bajar, hay una marea que no responde a ninguna luna. Facu fue el segundo Regente en cruzar el umbral y el único que volvió con el mar detrás. No lo domó: lo entendió. Sabe cuándo una corriente va a girar y cuándo una ola ya decidió romper. Por eso el agua llega antes que sus órdenes. Los guardianes del Acuático lo nombran en voz baja, como se nombra a la marea alta.',
  passive:['Mente de Marea','Flujo Corriente → Presión → Oleada: cada eslabón en orden sube la Marea (máx. 3), +20% de potencia y −15% de recarga a la siguiente. Con Marea 3, MAREA ALTA (8 s): básicos con ola, +15% de velocidad y doble área en la próxima. Romper el orden da Marea Baja y un escudo.'],
  weakness:'Sin secuencia su daño es moderado; Cabalgar la Ola no atraviesa muros.',
  voices:['La marea ya decidió. Yo solo la escucho.','El océano devuelve todo… menos a ellos.','Bajamar… por ahora…'],
  entryLine:'El océano no me obedece. Me reconoce.',
  setName:null,
  skins:[['Soberano de la Fosa','Manto de agua negra con bioluminiscencia violeta, corona de hueso de leviatán y quilla de obsidiana marina.','En la fosa más profunda, la luz la ponen los que viven allí. Facu aprendió a vestirse con ella.']],
  skills:[['Corriente de Resaca','current',22,5000,300,34,3500,3.0,'Abre una corriente en línea durante 3,5 s: arrastra a los comunes en su dirección y acelera a los aliados que la pisan. (Flujo: Corriente)','current'],
   ['Presión Abisal','pressure',24,7400,280,120,0,4.0,'Implosión en el punto elegido: atrae a los comunes al centro, daña y frena. Los jefes solo reciben daño y lentitud. (Flujo: Presión)','pressure'],
   ['Cabalgar la Ola','ride',24,7000,320,46,520,3.6,'Facu cabalga una ola a través de los enemigos: los aparta, deja espuma que frena y protege a los aliados que cruza. Se detiene ante muros y bordes. (Flujo: Oleada)','wave'],
   ['El Océano Reclama la Arena','ocean',0,64000,0,460,4200,5.6,'La arena se inunda: Facu se eleva sobre una ola, el remolino arrastra a la horda al centro, siluetas abisales cruzan bajo el agua y la ola final atraviesa el escenario. Nadie termina fuera de los límites.','all']]},

 aurelia:{name:'Aurelia',title:'La Arquitecta Solar',origin:'El templo solar del Laberinto',tagline:'Aurelia levanta nodos de luz sólida que se unen en triángulos y culmina en una catedral.',role:'mago',color:'#f2c14e',glow:'#fff1b8',stats:[98,12,.06,165,310,520,true],weapon:'Compás de Luz Sólida',arena:'laberinto',setName:'Planos del Mediodía',
  fantasy:'Maga constructora: levanta geometría de luz sólida y convierte el terreno en un plano que castiga a quien lo cruza.',
  silhouette:'Túnica de arquitecta con hombreras angulares, compás gigante a la espalda y tres prismas flotando en triángulo.',
  history:'Aurelia trazaba los planos del Laberinto cuando todavía era un templo al sol. Vio cómo la Horda torció los pasillos para que nadie encontrara la salida. No intentó romper las paredes: aprendió a dibujar otras encima, de luz sólida, que duran lo suficiente para que alguien pase. Lleva el compás de su maestra y una regla: toda estructura que levanta debe tener una puerta.',
  passive:['Convergencia','Sus habilidades dejan Nodos Solares (máx. 3). Con tres nodos se forma un triángulo de luz: los enemigos dentro reciben daño periódico y se frenan.'],
  weakness:'Necesita preparar nodos; sin ellos su daño en área es bajo.',
  voices:['Toda estructura empieza con un punto.','Medí dos veces. Iluminé una.','El plano… quedó sin terminar…'],
  skins:[['Vitral del Mediodía','Túnica de paneles de vitral emplomado, compás de plomo y prismas de colores en lugar de oro.','Los vidrieros del Laberinto le regalaron un manto hecho con las ventanas que salvó.'],['Catedral Corrupta','Armadura de piedra ennegrecida con grietas de luz roja y prismas de obsidiana.','Una vez dibujó una catedral para la Horda. Lleva sus restos para recordar que la luz también se puede torcer.']],
  skills:[['Prisma','prism',22,4200,280,40,9000,1.2,'Cristaliza un Nodo Solar en el punto elegido (máx. 3) con un pequeño estallido.','light'],
   ['Refracción','refract',26,6400,340,24,0,2.2,'Rayo en línea; cada nodo que toca lo refracta hacia el enemigo más cercano.','light'],
   ['Paso Luminal','luminal',24,8800,320,90,0,1.1,'Se traslada al nodo más lejano (o al punto elegido) y crea un nodo donde estaba.','light'],
   ['Catedral del Sol','cathedral',0,40000,0,170,6500,.8,'Los nodos se elevan en una catedral geométrica de luz: pulsos de daño dentro y regeneración para aliados.','light']]},
 khepri:{name:'Khepri',title:'El Portador del Enjambre',origin:'Las tumbas del Abismo',tagline:'Khepri lanza, recoge y viste a su enjambre de escarabajos; cada muerte cercana lo alimenta.',role:'asesino',color:'#3fae8a',glow:'#c8f27a',stats:[106,11,.08,182,78,440,false],weapon:'Hoces de Élitro',arena:'abismo',setName:'Caparazón del Ocaso',
  fantasy:'Asesino que comanda un enjambre visible: lo lanza, lo recoge y lo convierte en armadura.',
  silhouette:'Armadura ceremonial de escarabajo con élitros abiertos a la espalda, dos hoces curvas y un tocado con disco solar opaco.',
  history:'En el Abismo, los escarabajos son lo único que la Horda no logró corromper: se comen lo que ella deja. Khepri fue sacerdote de un culto que los alimentaba para mantener limpias las tumbas. Cuando la Horda llegó, el enjambre lo eligió a él. No lo obedece por miedo: lo sigue porque Khepri siempre sabe dónde hay carroña.',
  passive:['Carroñeros','Cada enemigo que muere cerca alimenta el enjambre (máx. 60 escarabajos). El enjambre es visible y potencia sus habilidades.'],
  weakness:'Con el enjambre vacío pierde gran parte de su daño en área.',
  voices:['Ellos ya huelen la cosecha.','Nada se desperdicia.','Mis escarabajos… se dispersan…'],
  skins:[['Escarabajo de Lapislázuli','Armadura de lapislázuli y oro, élitros de esmalte azul y enjambre de escarabajos dorados.','Los orfebres del Abismo forjaron su armadura con las joyas que la Horda no supo valorar.'],['Plaga de Ceniza','Caparazón gris ceniza agrietado, hoces de hueso y enjambre de polillas tiznadas.','Cuando el Infernal quemó su templo, el enjambre cambió de forma para sobrevivir.']],
  skills:[['Enjambre','swarm_send',24,6000,320,85,3000,1.6,'Envía el enjambre al punto elegido: atraviesa el campo, envuelve a los enemigos y vuelve.','swarm'],
   ['Caparazón Vivo','carapace',22,9000,0,0,4000,0,'Los escarabajos forman una armadura: escudo según el enjambre (consume 15).','swarm'],
   ['Vuelo de Élitros','elytra',24,7200,220,40,0,1.9,'Salto rasante: los escarabajos muerden todo lo que cruza.','swarm'],
   ['Eclipse de Escarabajos','eclipse',0,38000,0,210,6000,.75,'Khepri se descompone en enjambre y cubre una región: daño continuo y −60% de daño recibido mientras dura.','swarm']]},
 velmira:{name:'Velmira',title:'La Reina de las Máscaras',origin:'El viejo teatro de la Ciudad Maldita',tagline:'Velmira cambia entre cuatro máscaras: cada rostro es un estado y el cambio potencia el siguiente acto.',role:'soporte',color:'#c06bd8',glow:'#f3d1ff',stats:[104,9,.09,166,270,520,true],weapon:'Cetro de Bambalinas',arena:'ciudad',setName:'Función de Gala',
  fantasy:'Soporte de control: cada máscara es un estado mágico, y cambiar de rostro reescribe la próxima habilidad.',
  silhouette:'Reina de vestido de telón con cuello alto; cuatro máscaras flotan en semicírculo detrás de su cabeza.',
  history:'El teatro de la Ciudad cerró la noche del regreso, pero Velmira siguió dando funciones para los que se refugiaron en el escenario. Cuando el miedo era demasiado, les prestaba una máscara: quien se ponía la de la Valentía dejaba de temblar. Las máscaras aprendieron. Ahora flotan a su alrededor y cada una guarda la emoción de alguien que sobrevivió esa noche.',
  passive:['Mil Rostros','Lleva una máscara activa: Inspiración, Terror, Silencio o Protección. Cada habilidad aplica el efecto de la máscara; cambiar de rostro potencia la siguiente habilidad un 30%.'],
  weakness:'Poco daño propio; elegir mal la máscara desperdicia la ventana.',
  voices:['¿Qué rostro querés que te muestre?','El telón baja. Ustedes quedan.','Sin máscara… solo queda… mi cara…'],
  skins:[['Mascarada Veneciana','Vestido de terciopelo vino, máscaras doradas con plumas y cetro de cristal de Murano.','Una compañía itinerante le regaló el vestuario de su última obra, que nunca llegó a estrenarse.'],['Reina del Réquiem Blanco','Vestido de luto blanco, máscaras de porcelana agrietada y cetro de hueso.','Para la función de los ausentes, todas las máscaras se vuelven blancas.']],
  skills:[['Máscara Arrojada','mask_throw',22,4800,320,30,0,1.3,'Lanza la máscara activa en línea: daña y aplica su efecto a enemigos y aliados que toca.','mask'],
   ['Coro de Rostros','chorus',26,8600,0,170,0,.9,'Las máscaras giran a su alrededor: aliados reciben el beneficio y enemigos el castigo de la máscara activa.','mask'],
   ['Cambio de Rostro','face_swap',18,5200,140,90,0,.8,'Cambia a la siguiente máscara con un pequeño salto: la próxima habilidad se potencia un 30%.','mask'],
   ['El Gran Teatro','theatre',0,40000,0,260,5600,.9,'Cuatro máscaras espectrales gigantes actúan en secuencia: Inspiración, Terror, Silencio y Protección.','mask']]},
 vhal:{name:'Vhal',title:'El Astrónomo Caído',origin:'La torre de la Arena Gélida',tagline:'Vhal acumula Masa sobre la Horda hasta que los enemigos se atraen entre sí y colapsan.',role:'mago',color:'#6f7cf2',glow:'#d9e1ff',stats:[96,12,.05,162,320,560,true],weapon:'Astrolabio Roto',arena:'hielo',setName:'Carta Celeste',
  fantasy:'Mago gravitatorio: acumula Masa sobre la horda hasta que los enemigos se atraen entre sí y colapsan.',
  silhouette:'Astrónomo de túnica larga cuyo torso y brazos se abren a un cielo estrellado; astrolabio roto orbitando su mano.',
  history:'Vhal medía estrellas desde la torre más alta de la Gélida. La noche del regreso vio una caer hacia la arena y corrió a buscarla. La encontró viva. Desde entonces una parte de su cuerpo es cielo: se le ven las constelaciones debajo de la piel. Calcula órbitas para que la Horda se estrelle contra sí misma.',
  passive:['Masa Crítica','Sus habilidades acumulan Masa en los enemigos (máx. 5). Los enemigos con 3 o más Masa atraen poco a poco a los comunes cercanos.'],
  weakness:'Lento y frágil; la Masa tarda en acumularse.',
  voices:['Todo cae. La pregunta es hacia dónde.','Órbita cerrada.','Mi estrella… se apaga…'],
  skins:[['Eclipse Anular','Túnica negra con un anillo de fuego alrededor del pecho y astrolabio de oro.','En el eclipse más largo, Vhal vio la luz desde el borde. Desde entonces viste de sombra.'],['Nebulosa Carmesí','Cuerpo de nebulosa roja y rosa, túnica de seda estelar y astrolabio de cristal.','Cuando una estrella muere, deja un jardín. Vhal camina con uno puesto.']],
  skills:[['Estrella Errante','star_bolt',22,4400,360,26,0,1.8,'Proyectil estelar en línea: daña y añade 1 de Masa.','mass'],
   ['Pozo Gravitatorio','well',28,9000,300,130,3500,.55,'Pozo en el punto elegido: atrae comunes al centro y daña; la Masa aumenta la atracción.','mass'],
   ['Órbita','orbit',22,7800,220,60,0,1.2,'Se desplaza en arco alrededor del punto elegido dejando una estela que añade Masa.','mass'],
   ['Colapso','collapse',0,42000,320,190,4200,1.1,'Una estrella crece, se vuelve singularidad y colapsa: el estallido final escala con la Masa consumida.','mass']]},
 bront:{name:'Bront',title:'La Fortaleza Viviente',origin:'Las murallas de la Fortaleza',tagline:'Bront se desprende de placas protectoras, levanta murallas y se ancla como una ciudadela.',role:'tanque',color:'#8aa4b8',glow:'#bfe8ff',stats:[178,8,.22,132,90,640,false],weapon:'Puño de Bastión',arena:'fortaleza',setName:'Muralla Interior',
  fantasy:'Tanque que se desarma en placas defensivas y termina convertido en fortificación.',
  silhouette:'Armadura gigantesca y vacía; en el pecho, un cristal celeste flota donde debería estar el corazón. Placas sueltas orbitan sus hombros.',
  history:'Nadie recuerda quién vestía a Bront. En la Fábrica encontraron la armadura vacía, de pie, sosteniendo una puerta mientras los últimos obreros escapaban. El cristal de su pecho es un fragmento del Sello que el Forjador escondió allí. Bront no habla de sí mismo; habla de las puertas que todavía tiene que sostener.',
  passive:['Bastión','Al recibir daño desprende placas (una cada 2,5 s, máx. 4). Las placas protegen: aliados cerca reciben −12% de daño y enemigos que las tocan se frenan.'],
  weakness:'Muy lento; con Ciudadela no puede moverse.',
  voices:['Detrás de mí no pasa nadie.','La puerta sigue en pie.','Se… abre… la puerta…'],
  skins:[['Bastión de Bronce Ritual','Placas de bronce grabadas con plegarias, cristal ámbar y estandartes colgando de los hombros.','Los refugiados grabaron sus nombres en cada placa. Bront los lleva para que nadie los borre.'],['Coloso de Hielo Negro','Armadura de hielo negro, cristal blanco y placas que exhalan escarcha.','Sostuvo una puerta en la Gélida durante un invierno entero. El hielo se quedó con él.']],
  skills:[['Placa Arrojada','plate_throw',22,5000,280,32,0,1.6,'Lanza una placa que daña en línea y queda en el suelo como placa defensiva.','plate'],
   ['Muro de Placas','plate_wall',28,9400,160,26,5000,.45,'Levanta una muralla de placas frente a él: los enemigos que la cruzan reciben daño y se frenan mucho.','plate'],
   ['Pulso del Cristal','crystal_pulse',24,7600,0,120,0,1.5,'El cristal del pecho late: daña a su alrededor, aparta a los comunes y aturde un instante a los élites.','plate'],
   ['Ciudadela','citadel',0,42000,0,170,7000,.5,'Se ancla y se transforma en fortificación: +40% de reducción de daño, murallas alrededor y refugio para aliados.','plate']]},
 oriel:{name:'Oriel',title:'La Portera de las Cicatrices',origin:'Las grietas del Reino Fúngico',tagline:'Oriel abre pares de portales que sacan a su equipo del cerco de la Horda.',role:'soporte',color:'#e05a7a',glow:'#ffd0dc',stats:[102,10,.08,170,270,500,true],weapon:'Llave de las Cicatrices',arena:'micelial',setName:'Llaves del Umbral',
  fantasy:'Soporte de reposicionamiento: abre pares de portales a través de las Cicatrices de la Horda y convierte el mapa en un atajo para su equipo.',
  silhouette:'Portera de capa larga con capucha recortada, una llave ceremonial más alta que ella y dos aros de fractura flotando a los costados.',
  history:'Las Cicatrices de la Horda unen arenas que no deberían tocarse. Oriel trabajaba en la Fábrica marcando las grietas para que nadie cayera. Un día una se abrió bajo sus pies y salió del otro lado del Fúngico, viva. Desde entonces sabe dónde se puede pasar. No cierra las Cicatrices: las usa para llevar a los suyos lejos de la Horda antes de que la Horda llegue.',
  passive:['Paso entre Cicatrices','Los aliados que atraviesan sus portales salen del otro lado con escudo y +20% de velocidad (3 s). Los enemigos que los tocan son rechazados y dañados.'],
  weakness:'Depende de colocar bien los portales; poco daño directo.',
  voices:['Hay otro camino. Siempre lo hay.','Los traje a todos de vuelta.','La puerta… se cierra…'],
  skins:[['Llavera del Alba','Capa crema con bordes dorados, llave de cristal y aros de luz cálida.','En el primer amanecer después del regreso, Oriel abrió una Cicatriz hacia un campo de trigo. Nadie supo nunca dónde quedaba.'],['Guardiana del Ojo Rojo','Capa granate con capucha cerrada, llave de hierro negro y aros que sangran luz roja.','Hay Cicatrices que miran. Oriel aprendió a devolverles la mirada.']],
  skills:[['Abrir Cicatriz','portal',24,7000,320,38,6500,.9,'Abre un portal donde está y otro en el punto elegido. Aliados que entran salen por el otro; enemigos son rechazados.','rift'],
   ['Eco de la Cicatriz','rift_echo',24,6800,0,120,0,1.15,'Cada portal abierto pulsa: daña enemigos y cura un poco a los aliados cercanos.','rift'],
   ['Paso entre Mundos','rift_step',20,6200,300,70,0,1.2,'Oriel aparece en su otro portal (o en el punto elegido) y deja una grieta que daña.','rift'],
   ['La Gran Cicatriz','great_rift',0,40000,280,200,6000,.8,'Abre una Cicatriz gigante: enemigos dentro se frenan y reciben daño; ecos de campeones caídos salen a golpear y los aliados dentro reciben −20% de daño.','rift']]},
 saelis:{name:'Saelis',title:'La Heraldo del Plumaje',origin:'Las copas altas del Bosque',tagline:'Saelis siembra Plumas que bendicen a su equipo y las hace volar de vuelta contra la Horda.',role:'soporte',color:'#9cd0f0',glow:'#fff4cc',stats:[100,10,.07,172,280,520,true],weapon:'Báculo de Plumas',arena:'bosque',setName:'Plumaje del Heraldo',
  fantasy:'Soporte de bendiciones: deja Plumas en el suelo que aceleran y fortalecen a quien las recoge, y las convierte en proyectiles cuando la Horda se acerca.',
  silhouette:'Heraldo de túnica larga y báculo de pastora; dos alas de plumas a la espalda, un aro dorado detrás de la cabeza y hombreras redondas.',
  history:'Saelis cuidaba los nidos de las copas altas del Bosque cuando la Horda subió por los troncos. Las aves se fueron todas juntas, en una sola bandada, y le dejaron las plumas que perdieron al huir. Desde entonces las siembra en cada campo de batalla. Dice que una pluma en el suelo es una promesa: alguien va a volver a levantar vuelo.',
  passive:['Muda Celeste','Sus habilidades dejan Plumas en el suelo (máx. 8). Un aliado (nunca ella) que pisa una Pluma la absorbe y recibe la Bendición del Plumaje: +15% de velocidad y +8% de daño durante 3 s.'],
  weakness:'Sin curación ni escudos; depende de que su equipo recoja las Plumas a tiempo.',
  voices:['Que nadie se quede en el suelo.','Todos levantaron vuelo.','Se me cae… la última pluma…'],
  skins:[['Heraldo del Ocaso','Túnica granate, alas de plumas oscuras con puntas rosadas y un aro de fuego cobrizo.','Cuando el sol cae sobre el Bosque, Saelis siembra plumas rojas. Las que no se recogen antes de la noche arden solas.'],['Heraldo de la Aurora Boreal','Túnica verde agua, alas turquesa y un aro pálido que titila como el cielo del norte.','En la Gélida las plumas no caen: flotan. Saelis aprendió allí a esperar a que el cielo decida dónde dejarlas.']],
  skills:[['Abanico de Plumas','feather_fan',22,5200,300,22,8000,.75,'Lanza cinco plumas en abanico: cada una daña a los dos primeros enemigos que cruza y queda clavada en el suelo como Pluma.','feather'],
   ['Ráfaga Ascendente','updraft',26,8200,0,150,0,.8,'Bate las alas: aparta a los comunes, frena a los élites, bendice a los aliados cercanos y dispara cada Pluma cercana contra el enemigo más próximo.','feather'],
   ['Llamado del Plumaje','recall',20,7000,0,26,0,.6,'Todas sus Plumas vuelan de regreso: dañan a los enemigos del camino y cada una le acorta 0,2 s las recargas.','feather'],
   ['Cielo de Plumas','feather_sky',0,40000,260,220,5000,.6,'Abre un cielo sobre la zona: caen plumas sobre los enemigos de adentro, los aliados quedan bendecidos y al final seis Plumas quedan en el suelo.','feather']]}
};
